//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class AnimationTriggerPoint;
    class Variant;
}

#include <Urho3D/Graphics/Animation.h>

namespace UrhoBackend {


    public ref class AnimationTriggerPoint {
    public:
        AnimationTriggerPoint(Urho3D::AnimationTriggerPoint comp);
        AnimationTriggerPoint(System::IntPtr^ ptr);
        ~AnimationTriggerPoint();

// Properties
// Methods
// Fields
        property float time { float get(); void set(float value); }
        property Variant^ data { Variant^ get(); void set(Variant^ value); }

        Urho3D::AnimationTriggerPoint* animationtriggerpoint_;
    };
}
