//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "AnimationController.h"

#include <Urho3D/Graphics/AnimationController.h>
#include <Urho3D/Graphics/AnimationState.h>
#include "AnimationState.h"

namespace UrhoBackend {

AnimationController::AnimationController(Urho3D::AnimationController* fromUrho) : Component(fromUrho) { animationcontroller_ = fromUrho; }
AnimationController::AnimationController(System::IntPtr^ ptr) : AnimationController((Urho3D::AnimationController*)ptr->ToPointer()) { }

bool AnimationController::Play(System::String^ A, unsigned char B, bool C, float fadeTime)  { return  animationcontroller_->Play(Urho3D::String(ToCString(A)), B, C, fadeTime); }

bool AnimationController::PlayExclusive(System::String^ A, unsigned char B, bool C, float fadeTime)  { return  animationcontroller_->PlayExclusive(Urho3D::String(ToCString(A)), B, C, fadeTime); }

void AnimationController::Stop(System::String^ A, float fadeTime)  {  animationcontroller_->Stop(Urho3D::String(ToCString(A)), fadeTime); }

void AnimationController::StopLayer(unsigned char A, float fadeTime)  {  animationcontroller_->StopLayer(A, fadeTime); }

void AnimationController::StopAll(float fadeTime)  {  animationcontroller_->StopAll(fadeTime); }

bool AnimationController::Fade(System::String^ A, float B, float C)  { return  animationcontroller_->Fade(Urho3D::String(ToCString(A)), B, C); }

bool AnimationController::FadeOthers(System::String^ A, float B, float C)  { return  animationcontroller_->FadeOthers(Urho3D::String(ToCString(A)), B, C); }

bool AnimationController::SetLayer(System::String^ A, unsigned char B)  { return  animationcontroller_->SetLayer(Urho3D::String(ToCString(A)), B); }

bool AnimationController::SetStartBone(System::String^ A, System::String^ B)  { return  animationcontroller_->SetStartBone(Urho3D::String(ToCString(A)), Urho3D::String(ToCString(B))); }

bool AnimationController::SetTime(System::String^ A, float B)  { return  animationcontroller_->SetTime(Urho3D::String(ToCString(A)), B); }

bool AnimationController::SetWeight(System::String^ A, float B)  { return  animationcontroller_->SetWeight(Urho3D::String(ToCString(A)), B); }

bool AnimationController::SetLooped(System::String^ A, bool B)  { return  animationcontroller_->SetLooped(Urho3D::String(ToCString(A)), B); }

bool AnimationController::SetSpeed(System::String^ A, float B)  { return  animationcontroller_->SetSpeed(Urho3D::String(ToCString(A)), B); }

bool AnimationController::SetAutoFade(System::String^ A, float B)  { return  animationcontroller_->SetAutoFade(Urho3D::String(ToCString(A)), B); }

bool AnimationController::IsPlaying(System::String^ A)  { return  animationcontroller_->IsPlaying(Urho3D::String(ToCString(A))); }

bool AnimationController::IsFadingIn(System::String^ A)  { return  animationcontroller_->IsFadingIn(Urho3D::String(ToCString(A))); }

bool AnimationController::IsFadingOut(System::String^ A)  { return  animationcontroller_->IsFadingOut(Urho3D::String(ToCString(A))); }

unsigned char AnimationController::GetLayer(System::String^ A)  { return  animationcontroller_->GetLayer(Urho3D::String(ToCString(A))); }

System::String^ AnimationController::GetStartBone(System::String^ A)  { return  gcnew System::String(animationcontroller_->GetStartBoneName(Urho3D::String(ToCString(A))).CString()); }

float AnimationController::GetTime(System::String^ A)  { return  animationcontroller_->GetTime(Urho3D::String(ToCString(A))); }

float AnimationController::GetWeight(System::String^ A)  { return  animationcontroller_->GetWeight(Urho3D::String(ToCString(A))); }

bool AnimationController::GetLooped(System::String^ A)  { return  animationcontroller_->IsLooped(Urho3D::String(ToCString(A))); }

float AnimationController::GetLength(System::String^ A)  { return  animationcontroller_->GetLength(Urho3D::String(ToCString(A))); }

float AnimationController::GetSpeed(System::String^ A)  { return  animationcontroller_->GetSpeed(Urho3D::String(ToCString(A))); }

float AnimationController::GetAutoFade(System::String^ A)  { return  animationcontroller_->GetAutoFade(Urho3D::String(ToCString(A))); }

float AnimationController::GetFadeTarget(System::String^ A)  { return  animationcontroller_->GetFadeTarget(Urho3D::String(ToCString(A))); }

AnimationState^ AnimationController::GetAnimationState(System::String^ A)  { return  gcnew UrhoBackend::AnimationState(animationcontroller_->GetAnimationState(Urho3D::String(ToCString(A)))); }

AnimationState^ AnimationController::GetAnimationState(UrhoBackend::StringHash^ A)  { return  gcnew UrhoBackend::AnimationState(animationcontroller_->GetAnimationState(A->ToStringHash())); }

}
