//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "AnimatedModel.h"

#include <Urho3D/Graphics/AnimatedModel.h>
#include <Urho3D/Graphics/AnimationState.h>
#include "AnimationState.h"
#include <Urho3D/Graphics/Animation.h>
#include "Animation.h"
#include <Urho3D/Graphics/Zone.h>
#include "Zone.h"
#include <Urho3D/Graphics/Skeleton.h>
#include "Skeleton.h"

namespace UrhoBackend {

AnimatedModel::AnimatedModel(Urho3D::AnimatedModel* fromUrho) : StaticModel(fromUrho) { animatedmodel_ = fromUrho; }
AnimatedModel::AnimatedModel(System::IntPtr^ ptr) : AnimatedModel((Urho3D::AnimatedModel*)ptr->ToPointer()) { }

Zone^ AnimatedModel::zone::get() { return gcnew UrhoBackend::Zone(animatedmodel_->GetZone()); }
float AnimatedModel::animationLodBias::get() { return animatedmodel_->GetAnimationLodBias(); }
void AnimatedModel::animationLodBias::set(float value) { animatedmodel_->SetAnimationLodBias(value); }

bool AnimatedModel::updateInvisible::get() { return animatedmodel_->GetUpdateInvisible(); }
void AnimatedModel::updateInvisible::set(bool value) { animatedmodel_->SetUpdateInvisible(value); }

Skeleton^ AnimatedModel::skeleton::get() { return gcnew UrhoBackend::Skeleton(animatedmodel_->GetSkeleton()); }
unsigned AnimatedModel::numAnimationStates::get() { return animatedmodel_->GetNumAnimationStates(); }
AnimationState^ AnimatedModel::animationStates::get(System::String^ A) { return gcnew UrhoBackend::AnimationState(animatedmodel_->GetAnimationState(Urho3D::String(ToCString(A)))); }

unsigned AnimatedModel::numMorphs::get() { return animatedmodel_->GetNumMorphs(); }
float AnimatedModel::morphWeights::get(System::String^ A) { return animatedmodel_->GetMorphWeight(Urho3D::String(ToCString(A))); }

void AnimatedModel::morphWeights::set(System::String^ A, float B) { animatedmodel_->SetMorphWeight(Urho3D::String(ToCString(A)), B); }

AnimationState^ AnimatedModel::AddAnimationState(Animation^ A)  { return  gcnew UrhoBackend::AnimationState(animatedmodel_->AddAnimationState(A->animation_)); }

void AnimatedModel::RemoveAnimationState(Animation^ A)  {  animatedmodel_->RemoveAnimationState(A->animation_); }

void AnimatedModel::RemoveAnimationState(System::String^ A)  {  animatedmodel_->RemoveAnimationState(Urho3D::String(ToCString(A))); }

void AnimatedModel::RemoveAnimationState(AnimationState^ A)  {  animatedmodel_->RemoveAnimationState(A->animationstate_); }

void AnimatedModel::RemoveAnimationState(unsigned A)  {  animatedmodel_->RemoveAnimationState(A); }

void AnimatedModel::RemoveAllAnimationStates()  {  animatedmodel_->RemoveAllAnimationStates(); }

void AnimatedModel::SetMorphWeight(unsigned A, float B)  {  animatedmodel_->SetMorphWeight(A, B); }

void AnimatedModel::ResetMorphWeights()  {  animatedmodel_->ResetMorphWeights(); }

float AnimatedModel::GetMorphWeight(unsigned A)  { return  animatedmodel_->GetMorphWeight(A); }

AnimationState^ AnimatedModel::GetAnimationState(Animation^ A)  { return  gcnew UrhoBackend::AnimationState(animatedmodel_->GetAnimationState(A->animation_)); }

AnimationState^ AnimatedModel::GetAnimationState(unsigned A)  { return  gcnew UrhoBackend::AnimationState(animatedmodel_->GetAnimationState(A)); }

}
