//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class AnimationState;
    class String;
    class StringHash;
    class Bone;
    class Animation;
    class AnimatedModel;
    class Node;
}



namespace UrhoBackend {

    ref class Bone;
    ref class Animation;
    ref class AnimatedModel;

    public ref class AnimationState : public UrhoBackend::RefCounted {
    public:
        AnimationState(Urho3D::AnimationState* comp);
        AnimationState(System::IntPtr^ ptr);

// Properties
        property Bone^ startBone { Bone^ get(); void set(Bone^); }
        property bool looped { bool get(); void set(bool); }
        property float weight { float get(); void set(float); }
        property float time { float get(); void set(float); }
        property unsigned char layer { unsigned char get(); void set(unsigned char); }
        property Animation^ animation { Animation^ get(); }
        property AnimatedModel^ model { AnimatedModel^ get(); }
        property Node^ node { Node^ get(); }
        property bool enabled { bool get(); }
        property float length { float get(); }
        property float boneWeights[System::String^] { float get(System::String^); }
// Methods
        void AddWeight(float);
        void AddTime(float);
        void Apply();
        void SetBoneWeight(unsigned, float, bool);
        void SetBoneWeight(System::String^, float, bool);
        void SetBoneWeight(UrhoBackend::StringHash^, float, bool);
        float GetBoneWeight(unsigned);
        float GetBoneWeight(UrhoBackend::StringHash^);
        unsigned GetTrackIndex(System::String^);
        unsigned GetTrackIndex(UrhoBackend::StringHash^);
// Fields

        Urho3D::AnimationState* animationstate_;
    };
}
