//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class AnimatedSprite2D;
    class AnimationSet2D;
    class String;
}

#include "StaticSprite2D.h"

namespace UrhoBackend {

    ref class AnimationSet2D;

    public ref class AnimatedSprite2D : public UrhoBackend::StaticSprite2D {
    public:
        AnimatedSprite2D(Urho3D::AnimatedSprite2D* comp);
        AnimatedSprite2D(System::IntPtr^ ptr);

// Properties
        property float speed { float get(); void set(float); }
        property System::String^ animation { System::String^ get(); void set(System::String^); }
        property AnimationSet2D^ animationSet { AnimationSet2D^ get(); void set(AnimationSet2D^); }
        property LoopMode2D loopMode { LoopMode2D get(); void set(LoopMode2D); }
// Methods
        void SetAnimation(AnimationSet2D^, System::String^, LoopMode2D);
        void SetAnimation(System::String^, LoopMode2D);
// Fields

        Urho3D::AnimatedSprite2D* animatedsprite2d_;
    };
}
