//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Animatable.h"

#include <Urho3D/Scene/Animatable.h>
#include <Urho3D/Scene/ValueAnimation.h>
#include "ValueAnimation.h"
#include <Urho3D/Scene/ObjectAnimation.h>
#include "ObjectAnimation.h"
#include <Urho3D/Scene/AnimationDefs.h>

namespace UrhoBackend {

Animatable::Animatable(Urho3D::Animatable* fromUrho) : Serializable(fromUrho) { animatable_ = fromUrho; }
Animatable::Animatable(System::IntPtr^ ptr) : Animatable((Urho3D::Animatable*)ptr->ToPointer()) { }

bool Animatable::animationEnabled::get() { return animatable_->GetAnimationEnabled(); }
void Animatable::animationEnabled::set(bool value) { animatable_->SetAnimationEnabled(value); }

ObjectAnimation^ Animatable::objectAnimation::get() { return gcnew UrhoBackend::ObjectAnimation(animatable_->GetObjectAnimation()); }
void Animatable::objectAnimation::set(ObjectAnimation^ value) { animatable_->SetObjectAnimation(value->objectanimation_); }

void Animatable::SetAttributeAnimation(System::String^ A, ValueAnimation^ B, WrapMode wrapMod, float spee)  {  animatable_->SetAttributeAnimation(Urho3D::String(ToCString(A)), B->valueanimation_, (Urho3D::WrapMode)wrapMod, spee); }

ValueAnimation^ Animatable::GetAttributeAnimation(System::String^ A)  { return  gcnew UrhoBackend::ValueAnimation(animatable_->GetAttributeAnimation(Urho3D::String(ToCString(A)))); }

void Animatable::SetAttributeAnimationWrapMode(System::String^ A, WrapMode B)  {  animatable_->SetAttributeAnimationWrapMode(Urho3D::String(ToCString(A)), (Urho3D::WrapMode)B); }

WrapMode Animatable::GetAttributeAnimationWrapMode(System::String^ A)  { return  (UrhoBackend::WrapMode)animatable_->GetAttributeAnimationWrapMode(Urho3D::String(ToCString(A))); }

void Animatable::SetAttributeAnimationSpeed(System::String^ A, float B)  {  animatable_->SetAttributeAnimationSpeed(Urho3D::String(ToCString(A)), B); }

float Animatable::GetAttributeAnimationSpeed(System::String^ A)  { return  animatable_->GetAttributeAnimationSpeed(Urho3D::String(ToCString(A))); }

}
