//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class AnimationSet2D;
    class Animation2D;
    class String;
}

#include "Resource.h"

namespace UrhoBackend {

    ref class Animation2D;

    public ref class AnimationSet2D : public UrhoBackend::Resource {
    public:
        AnimationSet2D(Urho3D::AnimationSet2D* comp);
        AnimationSet2D(System::IntPtr^ ptr);

// Properties
        property unsigned numAnimations { unsigned get(); }
// Methods
        Animation2D^ GetAnimation(unsigned);
        Animation2D^ GetAnimation(System::String^);
// Fields

        Urho3D::AnimationSet2D* animationset2d_;
    };
}
