//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Animatable;
    class String;
    class ValueAnimation;
    class ObjectAnimation;
}



namespace UrhoBackend {

    ref class ValueAnimation;
    ref class ObjectAnimation;

    public ref class Animatable : public UrhoBackend::Serializable {
    public:
        Animatable(Urho3D::Animatable* comp);
        Animatable(System::IntPtr^ ptr);

// Properties
        property bool animationEnabled { bool get(); void set(bool); }
        property ObjectAnimation^ objectAnimation { ObjectAnimation^ get(); void set(ObjectAnimation^); }
// Methods
        void SetAttributeAnimation(System::String^, ValueAnimation^, WrapMode, float);
        ValueAnimation^ GetAttributeAnimation(System::String^);
        void SetAttributeAnimationWrapMode(System::String^, WrapMode);
        WrapMode GetAttributeAnimationWrapMode(System::String^);
        void SetAttributeAnimationSpeed(System::String^, float);
        float GetAttributeAnimationSpeed(System::String^);
// Fields

        Urho3D::Animatable* animatable_;
    };
}
