//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Billboard;
    class Vector3;
    class Vector2;
    class Rect;
    class Color;
}

#include <Urho3D/Graphics/BillboardSet.h>

namespace UrhoBackend {


    public ref class Billboard {
    public:
        Billboard(Urho3D::Billboard comp);
        Billboard(System::IntPtr^ ptr);
        ~Billboard();

// Properties
// Methods
// Fields
        property UrhoBackend::Vector3^ position { UrhoBackend::Vector3^ get(); void set(UrhoBackend::Vector3^ value); }
        property UrhoBackend::Vector2^ size { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^ value); }
        property Rect^ uv { Rect^ get(); void set(Rect^ value); }
        property UrhoBackend::Color^ color { UrhoBackend::Color^ get(); void set(UrhoBackend::Color^ value); }
        property float rotation { float get(); void set(float value); }
        property bool enabled { bool get(); void set(bool value); }

        Urho3D::Billboard* billboard_;
    };
}
