//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Billboard.h"

#include <Urho3D/Graphics/BillboardSet.h>

namespace UrhoBackend {

Billboard::Billboard(Urho3D::Billboard fromUrho) { billboard_ = new Urho3D::Billboard(); *billboard_ = fromUrho; }
Billboard::Billboard(System::IntPtr^ ptr) : Billboard(*((Urho3D::Billboard*)ptr->ToPointer())) { }
Billboard::~Billboard() { delete billboard_; }
UrhoBackend::Vector3^ Billboard::position::get() { return gcnew UrhoBackend::Vector3(billboard_->position_); }
void Billboard::position::set(UrhoBackend::Vector3^ value) { billboard_->position_ = value->ToVector3(); }

UrhoBackend::Vector2^ Billboard::size::get() { return gcnew UrhoBackend::Vector2(billboard_->size_); }
void Billboard::size::set(UrhoBackend::Vector2^ value) { billboard_->size_ = value->ToVector2(); }

Rect^ Billboard::uv::get() { return gcnew UrhoBackend::Rect(billboard_->uv_); }
void Billboard::uv::set(Rect^ value) { billboard_->uv_ = value->ToRect(); }

UrhoBackend::Color^ Billboard::color::get() { return gcnew Color(billboard_->color_); }
void Billboard::color::set(UrhoBackend::Color^ value) { billboard_->color_ = value->ToColor(); }

float Billboard::rotation::get() { return billboard_->rotation_; }
void Billboard::rotation::set(float value) { billboard_->rotation_ = value; }

bool Billboard::enabled::get() { return billboard_->enabled_; }
void Billboard::enabled::set(bool value) { billboard_->enabled_ = value; }

}
