//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Bone.h"

#include <Urho3D/Graphics/Skeleton.h>
#include <Urho3D/Math/BoundingBox.h>
#include "BoundingBox.h"

namespace UrhoBackend {

Bone::Bone(Urho3D::Bone fromUrho) { bone_ = new Urho3D::Bone(); *bone_ = fromUrho; }
Bone::Bone(System::IntPtr^ ptr) : Bone(*((Urho3D::Bone*)ptr->ToPointer())) { }
Bone::~Bone() { delete bone_; }
System::String^ Bone::name::get() { return gcnew System::String(bone_->name_.CString()); }
void Bone::name::set(System::String^ value) { bone_->name_ = Urho3D::String(ToCString(value)); }

UrhoBackend::Vector3^ Bone::initialPosition::get() { return gcnew UrhoBackend::Vector3(bone_->initialPosition_); }
void Bone::initialPosition::set(UrhoBackend::Vector3^ value) { bone_->initialPosition_ = value->ToVector3(); }

UrhoBackend::Quaternion^ Bone::initialRotation::get() { return gcnew UrhoBackend::Quaternion(bone_->initialRotation_); }
void Bone::initialRotation::set(UrhoBackend::Quaternion^ value) { bone_->initialRotation_ = value->ToQuaternion(); }

UrhoBackend::Vector3^ Bone::initialScale::get() { return gcnew UrhoBackend::Vector3(bone_->initialScale_); }
void Bone::initialScale::set(UrhoBackend::Vector3^ value) { bone_->initialScale_ = value->ToVector3(); }

bool Bone::animated::get() { return bone_->animated_; }
void Bone::animated::set(bool value) { bone_->animated_ = value; }

float Bone::radius::get() { return bone_->radius_; }
void Bone::radius::set(float value) { bone_->radius_ = value; }

BoundingBox^ Bone::boundingBox::get() { return gcnew UrhoBackend::BoundingBox(bone_->boundingBox_); }
void Bone::boundingBox::set(BoundingBox^ value) { bone_->boundingBox_ = *value->boundingbox_; }

}
