//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Button;
    class Texture;
    class IntRect;
    class IntVector2;
}



namespace UrhoBackend {

    ref class Texture;

    public ref class Button : public UrhoBackend::UIElement {
    public:
        Button(Urho3D::Button* comp);
        Button(System::IntPtr^ ptr);

// Properties
        property Texture^ texture { Texture^ get(); void set(Texture^); }
        property UrhoBackend::IntRect^ imageRect { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntRect^ border { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntRect^ imageBorder { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntVector2^ hoverOffset { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^); }
        property BlendMode blendMode { BlendMode get(); void set(BlendMode); }
        property bool tiled { bool get(); void set(bool); }
        property UrhoBackend::IntVector2^ pressedOffset { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^); }
        property UrhoBackend::IntVector2^ pressedChildOffset { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^); }
        property float repeatDelay { float get(); void set(float); }
        property float repeatRate { float get(); void set(float); }
        property bool pressed { bool get(); }
// Methods
        void SetFullImageRect();
        void SetHoverOffset(int, int);
        void SetPressedOffset(int, int);
        void SetPressedChildOffset(int, int);
        void SetRepeat(float, float);
// Fields

        Urho3D::Button* button_;
    };
}
