//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "CollisionEdge2D.h"

#include <Urho3D/Urho2D/CollisionEdge2D.h>

namespace UrhoBackend {

CollisionEdge2D::CollisionEdge2D(Urho3D::CollisionEdge2D* fromUrho) : CollisionShape2D(fromUrho) { collisionedge2d_ = fromUrho; }
CollisionEdge2D::CollisionEdge2D(System::IntPtr^ ptr) : CollisionEdge2D((Urho3D::CollisionEdge2D*)ptr->ToPointer()) { }

UrhoBackend::Vector2^ CollisionEdge2D::vertex1::get() { return gcnew UrhoBackend::Vector2(collisionedge2d_->GetVertex1()); }
void CollisionEdge2D::vertex1::set(UrhoBackend::Vector2^ value) { collisionedge2d_->SetVertex1(value->ToVector2()); }

UrhoBackend::Vector2^ CollisionEdge2D::vertex2::get() { return gcnew UrhoBackend::Vector2(collisionedge2d_->GetVertex2()); }
void CollisionEdge2D::vertex2::set(UrhoBackend::Vector2^ value) { collisionedge2d_->SetVertex2(value->ToVector2()); }

void CollisionEdge2D::SetVertices(UrhoBackend::Vector2^ A, UrhoBackend::Vector2^ B)  {  collisionedge2d_->SetVertices(A->ToVector2(), B->ToVector2()); }

}
