//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class CollisionCircle2D;
    class Vector2;
}

#include "CollisionShape2D.h"

namespace UrhoBackend {


    public ref class CollisionCircle2D : public UrhoBackend::CollisionShape2D {
    public:
        CollisionCircle2D(Urho3D::CollisionCircle2D* comp);
        CollisionCircle2D(System::IntPtr^ ptr);

// Properties
        property float radius { float get(); void set(float); }
        property UrhoBackend::Vector2^ center { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
// Methods
        void SetCenter(float, float);
// Fields

        Urho3D::CollisionCircle2D* collisioncircle2d_;
    };
}
