//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "CollisionPolygon2D.h"

#include <Urho3D/Urho2D/CollisionPolygon2D.h>

namespace UrhoBackend {

CollisionPolygon2D::CollisionPolygon2D(Urho3D::CollisionPolygon2D* fromUrho) : CollisionShape2D(fromUrho) { collisionpolygon2d_ = fromUrho; }
CollisionPolygon2D::CollisionPolygon2D(System::IntPtr^ ptr) : CollisionPolygon2D((Urho3D::CollisionPolygon2D*)ptr->ToPointer()) { }

unsigned CollisionPolygon2D::vertexCount::get() { return collisionpolygon2d_->GetVertexCount(); }
void CollisionPolygon2D::vertexCount::set(unsigned value) { collisionpolygon2d_->SetVertexCount(value); }

void CollisionPolygon2D::SetVertex(unsigned A, UrhoBackend::Vector2^ B)  {  collisionpolygon2d_->SetVertex(A, B->ToVector2()); }

UrhoBackend::Vector2^ CollisionPolygon2D::GetVertex(unsigned A)  { return  gcnew UrhoBackend::Vector2(collisionpolygon2d_->GetVertex(A)); }

}
