//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class CollisionBox2D;
    class Vector2;
}

#include "CollisionShape2D.h"

namespace UrhoBackend {


    public ref class CollisionBox2D : public UrhoBackend::CollisionShape2D {
    public:
        CollisionBox2D(Urho3D::CollisionBox2D* comp);
        CollisionBox2D(System::IntPtr^ ptr);

// Properties
        property UrhoBackend::Vector2^ size { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
        property UrhoBackend::Vector2^ center { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
        property float angle { float get(); void set(float); }
// Methods
        void SetSize(float, float);
        void SetCenter(float, float);
// Fields

        Urho3D::CollisionBox2D* collisionbox2d_;
    };
}
