//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class CollisionChain2D;
    class Vector2;
}

#include "CollisionShape2D.h"

namespace UrhoBackend {


    public ref class CollisionChain2D : public UrhoBackend::CollisionShape2D {
    public:
        CollisionChain2D(Urho3D::CollisionChain2D* comp);
        CollisionChain2D(System::IntPtr^ ptr);

// Properties
        property bool loop { bool get(); void set(bool); }
        property unsigned vertexCount { unsigned get(); void set(unsigned); }
// Methods
        void SetVertex(unsigned, UrhoBackend::Vector2^);
        UrhoBackend::Vector2^ GetVertex(unsigned);
// Fields

        Urho3D::CollisionChain2D* collisionchain2d_;
    };
}
