//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class CollisionEdge2D;
    class Vector2;
}

#include "CollisionShape2D.h"

namespace UrhoBackend {


    public ref class CollisionEdge2D : public UrhoBackend::CollisionShape2D {
    public:
        CollisionEdge2D(Urho3D::CollisionEdge2D* comp);
        CollisionEdge2D(System::IntPtr^ ptr);

// Properties
        property UrhoBackend::Vector2^ vertex1 { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
        property UrhoBackend::Vector2^ vertex2 { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
// Methods
        void SetVertices(UrhoBackend::Vector2^, UrhoBackend::Vector2^);
// Fields

        Urho3D::CollisionEdge2D* collisionedge2d_;
    };
}
