//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "CollisionCircle2D.h"

#include <Urho3D/Urho2D/CollisionCircle2D.h>

namespace UrhoBackend {

CollisionCircle2D::CollisionCircle2D(Urho3D::CollisionCircle2D* fromUrho) : CollisionShape2D(fromUrho) { collisioncircle2d_ = fromUrho; }
CollisionCircle2D::CollisionCircle2D(System::IntPtr^ ptr) : CollisionCircle2D((Urho3D::CollisionCircle2D*)ptr->ToPointer()) { }

float CollisionCircle2D::radius::get() { return collisioncircle2d_->GetRadius(); }
void CollisionCircle2D::radius::set(float value) { collisioncircle2d_->SetRadius(value); }

UrhoBackend::Vector2^ CollisionCircle2D::center::get() { return gcnew UrhoBackend::Vector2(collisioncircle2d_->GetCenter()); }
void CollisionCircle2D::center::set(UrhoBackend::Vector2^ value) { collisioncircle2d_->SetCenter(value->ToVector2()); }

void CollisionCircle2D::SetCenter(float A, float B)  {  collisioncircle2d_->SetCenter(A, B); }

}
