//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "CollisionBox2D.h"

#include <Urho3D/Urho2D/CollisionBox2D.h>

namespace UrhoBackend {

CollisionBox2D::CollisionBox2D(Urho3D::CollisionBox2D* fromUrho) : CollisionShape2D(fromUrho) { collisionbox2d_ = fromUrho; }
CollisionBox2D::CollisionBox2D(System::IntPtr^ ptr) : CollisionBox2D((Urho3D::CollisionBox2D*)ptr->ToPointer()) { }

UrhoBackend::Vector2^ CollisionBox2D::size::get() { return gcnew UrhoBackend::Vector2(collisionbox2d_->GetSize()); }
void CollisionBox2D::size::set(UrhoBackend::Vector2^ value) { collisionbox2d_->SetSize(value->ToVector2()); }

UrhoBackend::Vector2^ CollisionBox2D::center::get() { return gcnew UrhoBackend::Vector2(collisionbox2d_->GetCenter()); }
void CollisionBox2D::center::set(UrhoBackend::Vector2^ value) { collisionbox2d_->SetCenter(value->ToVector2()); }

float CollisionBox2D::angle::get() { return collisionbox2d_->GetAngle(); }
void CollisionBox2D::angle::set(float value) { collisionbox2d_->SetAngle(value); }

void CollisionBox2D::SetSize(float A, float B)  {  collisionbox2d_->SetSize(A, B); }

void CollisionBox2D::SetCenter(float A, float B)  {  collisionbox2d_->SetCenter(A, B); }

}
