//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

namespace Urho3D {
    class ColorFrame;
    class Color;
}

#include <Urho3D/Graphics/ParticleEffect.h>

namespace UrhoBackend {

    ref class ParticleEffect;

    public ref class ColorFrame {
    public:
        ColorFrame(Urho3D::ColorFrame comp, ParticleEffect^ effect);
        ~ColorFrame();

// Properties
// Methods
// Fields
        property UrhoBackend::Color^ color { UrhoBackend::Color^ get(); void set(UrhoBackend::Color^ value); }
        property float time { float get(); void set(float value); }

        Urho3D::ColorFrame* colorframe_;
        ParticleEffect^ effect_;
    };
}
