//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class ConstraintRope2D;
    class Vector2;
}

#include "Constraint2D.h"

namespace UrhoBackend {


    public ref class ConstraintRope2D : public UrhoBackend::Constraint2D {
    public:
        ConstraintRope2D(Urho3D::ConstraintRope2D* comp);
        ConstraintRope2D(System::IntPtr^ ptr);

// Properties
        property UrhoBackend::Vector2^ ownerBodyAnchor { void set(UrhoBackend::Vector2^); }
        property UrhoBackend::Vector2^ ownerBodyAnchor { UrhoBackend::Vector2^ get(); }
        property UrhoBackend::Vector2^ otherBodyAnchor { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
        property float maxLength { float get(); void set(float); }
// Methods
// Fields

        Urho3D::ConstraintRope2D* constraintrope2d_;
    };
}
