//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "ConstraintDistance2D.h"

#include <Urho3D/Urho2D/ConstraintDistance2D.h>

namespace UrhoBackend {

ConstraintDistance2D::ConstraintDistance2D(Urho3D::ConstraintDistance2D* fromUrho) : Constraint2D(fromUrho) { constraintdistance2d_ = fromUrho; }
ConstraintDistance2D::ConstraintDistance2D(System::IntPtr^ ptr) : ConstraintDistance2D((Urho3D::ConstraintDistance2D*)ptr->ToPointer()) { }

void ConstraintDistance2D::ownerBodyAnchor::set(UrhoBackend::Vector2^ value) { constraintdistance2d_->SetOwnerBodyAnchor(value->ToVector2()); }

UrhoBackend::Vector2^ ConstraintDistance2D::ownerBodyAnchor::get() { return gcnew UrhoBackend::Vector2(constraintdistance2d_->GetOwnerBodyAnchor()); }
UrhoBackend::Vector2^ ConstraintDistance2D::otherBodyAnchor::get() { return gcnew UrhoBackend::Vector2(constraintdistance2d_->GetOtherBodyAnchor()); }
void ConstraintDistance2D::otherBodyAnchor::set(UrhoBackend::Vector2^ value) { constraintdistance2d_->SetOtherBodyAnchor(value->ToVector2()); }

float ConstraintDistance2D::frequencyHz::get() { return constraintdistance2d_->GetFrequencyHz(); }
void ConstraintDistance2D::frequencyHz::set(float value) { constraintdistance2d_->SetFrequencyHz(value); }

float ConstraintDistance2D::dampingRatio::get() { return constraintdistance2d_->GetDampingRatio(); }
void ConstraintDistance2D::dampingRatio::set(float value) { constraintdistance2d_->SetDampingRatio(value); }

}
