//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Console.h"

#include <Urho3D/Engine/Console.h>
#include <Urho3D/Resource/XMLFile.h>
#include "XMLFile.h"
#include <Urho3D/UI/BorderImage.h>
#include "BorderImage.h"
#include <Urho3D/UI/LineEdit.h>
#include "LineEdit.h"
#include <Urho3D/UI/Button.h>
#include "Button.h"

namespace UrhoBackend {

Console::Console(Urho3D::Console* fromUrho) : Object(fromUrho) { console_ = fromUrho; }
Console::Console(System::IntPtr^ ptr) : Console((Urho3D::Console*)ptr->ToPointer()) { }

XMLFile^ Console::defaultStyle::get() { return gcnew UrhoBackend::XMLFile(console_->GetDefaultStyle()); }
void Console::defaultStyle::set(XMLFile^ value) { console_->SetDefaultStyle(value->xmlfile_); }

bool Console::visible::get() { return console_->IsVisible(); }
void Console::visible::set(bool value) { console_->SetVisible(value); }

bool Console::autoVisibleOnError::get() { return console_->IsAutoVisibleOnError(); }
void Console::autoVisibleOnError::set(bool value) { console_->SetAutoVisibleOnError(value); }

System::String^ Console::commandInterpreter::get() { return gcnew System::String(console_->GetCommandInterpreter().CString()); }
void Console::commandInterpreter::set(System::String^ value) { console_->SetCommandInterpreter(Urho3D::String(ToCString(value))); }

unsigned Console::numBufferedRows::get() { return console_->GetNumBufferedRows(); }
void Console::numBufferedRows::set(unsigned value) { console_->SetNumBufferedRows(value); }

unsigned Console::numRows::get() { return console_->GetNumRows(); }
void Console::numRows::set(unsigned value) { console_->SetNumRows(value); }

unsigned Console::numHistoryRows::get() { return console_->GetNumHistoryRows(); }
void Console::numHistoryRows::set(unsigned value) { console_->SetNumHistoryRows(value); }

bool Console::focusOnShow::get() { return console_->GetFocusOnShow(); }
void Console::focusOnShow::set(bool value) { console_->SetFocusOnShow(value); }

unsigned Console::historyPosition::get() { return console_->GetHistoryPosition(); }
System::String^ Console::historyRow::get(unsigned A) { return gcnew System::String(console_->GetHistoryRow(A).CString()); }

BorderImage^ Console::background::get() { return gcnew UrhoBackend::BorderImage(console_->GetBackground()); }
LineEdit^ Console::lineEdit::get() { return gcnew UrhoBackend::LineEdit(console_->GetLineEdit()); }
Button^ Console::closeButton::get() { return gcnew UrhoBackend::Button(console_->GetCloseButton()); }
void Console::Toggle()  {  console_->Toggle(); }

void Console::UpdateElements()  {  console_->UpdateElements(); }

void Console::CopySelectedRows()  {  console_->CopySelectedRows(); }

}
