//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class ConstraintMotor2D;
    class Vector2;
}

#include "Constraint2D.h"

namespace UrhoBackend {


    public ref class ConstraintMotor2D : public UrhoBackend::Constraint2D {
    public:
        ConstraintMotor2D(Urho3D::ConstraintMotor2D* comp);
        ConstraintMotor2D(System::IntPtr^ ptr);

// Properties
        property UrhoBackend::Vector2^ linearOffset { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
        property float angularOffset { float get(); void set(float); }
        property float maxForce { float get(); void set(float); }
        property float maxTorque { float get(); void set(float); }
        property float correctionFactor { float get(); void set(float); }
// Methods
// Fields

        Urho3D::ConstraintMotor2D* constraintmotor2d_;
    };
}
