//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class ConstraintMouse2D;
    class Vector2;
}

#include "Constraint2D.h"

namespace UrhoBackend {


    public ref class ConstraintMouse2D : public UrhoBackend::Constraint2D {
    public:
        ConstraintMouse2D(Urho3D::ConstraintMouse2D* comp);
        ConstraintMouse2D(System::IntPtr^ ptr);

// Properties
        property UrhoBackend::Vector2^ target { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
        property float maxForce { float get(); void set(float); }
        property float frequencyHz { float get(); void set(float); }
        property float dampingRatio { float get(); void set(float); }
// Methods
// Fields

        Urho3D::ConstraintMouse2D* constraintmouse2d_;
    };
}
