//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "ConstraintMotor2D.h"

#include <Urho3D/Urho2D/ConstraintMotor2D.h>

namespace UrhoBackend {

ConstraintMotor2D::ConstraintMotor2D(Urho3D::ConstraintMotor2D* fromUrho) : Constraint2D(fromUrho) { constraintmotor2d_ = fromUrho; }
ConstraintMotor2D::ConstraintMotor2D(System::IntPtr^ ptr) : ConstraintMotor2D((Urho3D::ConstraintMotor2D*)ptr->ToPointer()) { }

UrhoBackend::Vector2^ ConstraintMotor2D::linearOffset::get() { return gcnew UrhoBackend::Vector2(constraintmotor2d_->GetLinearOffset()); }
void ConstraintMotor2D::linearOffset::set(UrhoBackend::Vector2^ value) { constraintmotor2d_->SetLinearOffset(value->ToVector2()); }

float ConstraintMotor2D::angularOffset::get() { return constraintmotor2d_->GetAngularOffset(); }
void ConstraintMotor2D::angularOffset::set(float value) { constraintmotor2d_->SetAngularOffset(value); }

float ConstraintMotor2D::maxForce::get() { return constraintmotor2d_->GetMaxForce(); }
void ConstraintMotor2D::maxForce::set(float value) { constraintmotor2d_->SetMaxForce(value); }

float ConstraintMotor2D::maxTorque::get() { return constraintmotor2d_->GetMaxTorque(); }
void ConstraintMotor2D::maxTorque::set(float value) { constraintmotor2d_->SetMaxTorque(value); }

float ConstraintMotor2D::correctionFactor::get() { return constraintmotor2d_->GetCorrectionFactor(); }
void ConstraintMotor2D::correctionFactor::set(float value) { constraintmotor2d_->SetCorrectionFactor(value); }

}
