//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class ConstraintPrismatic2D;
    class Vector2;
}

#include "Constraint2D.h"

namespace UrhoBackend {


    public ref class ConstraintPrismatic2D : public UrhoBackend::Constraint2D {
    public:
        ConstraintPrismatic2D(Urho3D::ConstraintPrismatic2D* comp);
        ConstraintPrismatic2D(System::IntPtr^ ptr);

// Properties
        property UrhoBackend::Vector2^ anchor { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
        property UrhoBackend::Vector2^ axis { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^); }
        property bool enableLimit { bool get(); void set(bool); }
        property float lowerTranslation { float get(); void set(float); }
        property float upperTranslation { float get(); void set(float); }
        property bool enableMotor { bool get(); void set(bool); }
        property float maxMotorForce { float get(); void set(float); }
        property float motorSpeed { float get(); void set(float); }
// Methods
// Fields

        Urho3D::ConstraintPrismatic2D* constraintprismatic2d_;
    };
}
