//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Console;
    class XMLFile;
    class String;
    class BorderImage;
    class LineEdit;
    class Button;
}



namespace UrhoBackend {

    ref class XMLFile;
    ref class BorderImage;
    ref class LineEdit;
    ref class Button;

    public ref class Console : public UrhoBackend::Object {
    public:
        Console(Urho3D::Console* comp);
        Console(System::IntPtr^ ptr);

// Properties
        property XMLFile^ defaultStyle { XMLFile^ get(); void set(XMLFile^); }
        property bool visible { bool get(); void set(bool); }
        property bool autoVisibleOnError { bool get(); void set(bool); }
        property System::String^ commandInterpreter { System::String^ get(); void set(System::String^); }
        property unsigned numBufferedRows { unsigned get(); void set(unsigned); }
        property unsigned numRows { unsigned get(); void set(unsigned); }
        property unsigned numHistoryRows { unsigned get(); void set(unsigned); }
        property bool focusOnShow { bool get(); void set(bool); }
        property unsigned historyPosition { unsigned get(); }
        property System::String^ historyRow[unsigned] { System::String^ get(unsigned); }
        property BorderImage^ background { BorderImage^ get(); }
        property LineEdit^ lineEdit { LineEdit^ get(); }
        property Button^ closeButton { Button^ get(); }
// Methods
        void Toggle();
        void UpdateElements();
        void CopySelectedRows();
// Fields

        Urho3D::Console* console_;
    };
}
