//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Controls;
    class VariantMap;
}

#include <Urho3D/Input/Controls.h>

namespace UrhoBackend {


    public ref class Controls {
    public:
        Controls(Urho3D::Controls comp);
        Controls(System::IntPtr^ ptr);
        ~Controls();

// Properties
// Methods
        Controls^ opAssign(Controls^);
        void Reset();
        void Set(unsigned, bool);
        bool IsDown(unsigned);
        bool IsPressed(unsigned, Controls^);
// Fields
        property unsigned buttons { unsigned get(); void set(unsigned value); }
        property float yaw { float get(); void set(float value); }
        property float pitch { float get(); void set(float value); }
        property UrhoBackend::VariantMap^ extraData { UrhoBackend::VariantMap^ get(); void set(UrhoBackend::VariantMap^ value); }

        Urho3D::Controls* controls_;
    };
}
