//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Cursor;
    class String;
    class Texture;
    class IntRect;
    class IntVector2;
}



namespace UrhoBackend {

    ref class Texture;

    public ref class Cursor : public UrhoBackend::UIElement {
    public:
        Cursor(Urho3D::Cursor* comp);
        Cursor(System::IntPtr^ ptr);

// Properties
        property Texture^ texture { Texture^ get(); void set(Texture^); }
        property UrhoBackend::IntRect^ imageRect { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntRect^ border { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntRect^ imageBorder { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntVector2^ hoverOffset { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^); }
        property BlendMode blendMode { BlendMode get(); void set(BlendMode); }
        property bool tiled { bool get(); void set(bool); }
        property System::String^ shape { System::String^ get(); void set(System::String^); }
        property bool useSystemShapes { bool get(); void set(bool); }
// Methods
        void SetFullImageRect();
        void SetHoverOffset(int, int);
        void DefineShape(System::String^, Texture^, UrhoBackend::IntRect^, UrhoBackend::IntVector2^);
        void DefineShape(CursorShape, Texture^, UrhoBackend::IntRect^, UrhoBackend::IntVector2^);
        void SetShape(System::String^);
        void SetShape(CursorShape);
// Fields

        Urho3D::Cursor* cursor_;
    };
}
