//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "CustomGeometryVertex.h"

#include <Urho3D/Graphics/CustomGeometry.h>

namespace UrhoBackend {

CustomGeometryVertex::CustomGeometryVertex(Urho3D::CustomGeometryVertex fromUrho) { customgeometryvertex_ = new Urho3D::CustomGeometryVertex(); *customgeometryvertex_ = fromUrho; }
CustomGeometryVertex::CustomGeometryVertex(System::IntPtr^ ptr) : CustomGeometryVertex(*((Urho3D::CustomGeometryVertex*)ptr->ToPointer())) { }
CustomGeometryVertex::~CustomGeometryVertex() { delete customgeometryvertex_; }
UrhoBackend::Vector3^ CustomGeometryVertex::position::get() { return gcnew UrhoBackend::Vector3(customgeometryvertex_->position_); }
void CustomGeometryVertex::position::set(UrhoBackend::Vector3^ value) { customgeometryvertex_->position_ = value->ToVector3(); }

UrhoBackend::Vector3^ CustomGeometryVertex::normal::get() { return gcnew UrhoBackend::Vector3(customgeometryvertex_->normal_); }
void CustomGeometryVertex::normal::set(UrhoBackend::Vector3^ value) { customgeometryvertex_->normal_ = value->ToVector3(); }

unsigned CustomGeometryVertex::color::get() { return customgeometryvertex_->color_; }
void CustomGeometryVertex::color::set(unsigned value) { customgeometryvertex_->color_ = value; }

UrhoBackend::Vector2^ CustomGeometryVertex::texCoord::get() { return gcnew UrhoBackend::Vector2(customgeometryvertex_->texCoord_); }
void CustomGeometryVertex::texCoord::set(UrhoBackend::Vector2^ value) { customgeometryvertex_->texCoord_ = value->ToVector2(); }

UrhoBackend::Vector4^ CustomGeometryVertex::tangent::get() { return gcnew UrhoBackend::Vector4(customgeometryvertex_->tangent_); }
void CustomGeometryVertex::tangent::set(UrhoBackend::Vector4^ value) { customgeometryvertex_->tangent_ = value->ToVector4(); }

}
