//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class CustomGeometry;
    class Vector3;
    class Color;
    class Vector2;
    class Vector4;
    class CustomGeometryVertex;
    class Material;
    class Zone;
}

#include "Drawable.h"

namespace UrhoBackend {

    ref class CustomGeometryVertex;
    ref class Material;
    ref class Zone;

    public ref class CustomGeometry : public UrhoBackend::Drawable {
    public:
        CustomGeometry(Urho3D::CustomGeometry* comp);
        CustomGeometry(System::IntPtr^ ptr);

// Properties
        property bool dynamic { bool get(); void set(bool); }
        property Material^ materials[unsigned] { Material^ get(unsigned); void set(unsigned, Material^); }
        property bool materials[unsigned, Material^] { void set(unsigned, Material^, bool); }
        property unsigned numGeometries { unsigned get(); void set(unsigned); }
        property unsigned numVertices[unsigned] { unsigned get(unsigned); }
        property Zone^ zone { Zone^ get(); }
// Methods
        void Clear();
        void BeginGeometry(unsigned, PrimitiveType);
        void DefineVertex(UrhoBackend::Vector3^);
        void DefineNormal(UrhoBackend::Vector3^);
        void DefineColor(UrhoBackend::Color^);
        void DefineTexCoord(UrhoBackend::Vector2^);
        void DefineTangent(UrhoBackend::Vector4^);
        void DefineGeometry(unsigned, PrimitiveType, unsigned, bool, bool, bool, bool);
        void Commit();
        CustomGeometryVertex^ GetVertex(unsigned, unsigned);
// Fields

        Urho3D::CustomGeometry* customgeometry_;
    };
}
