//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class DetourCrowdManager;
    class NavigationMesh;
}



namespace UrhoBackend {

    ref class NavigationMesh;

    public ref class DetourCrowdManager : public UrhoBackend::Component {
    public:
        DetourCrowdManager(Urho3D::DetourCrowdManager* comp);
        DetourCrowdManager(System::IntPtr^ ptr);

// Properties
        property NavigationMesh^ navMesh { NavigationMesh^ get(); void set(NavigationMesh^); }
        property int maxAgents { int get(); void set(int); }
// Methods
        void CreateCrowd();
        void SetAreaCost(unsigned, unsigned, float);
        float GetAreaCost(unsigned, unsigned);
// Fields

        Urho3D::DetourCrowdManager* detourcrowdmanager_;
    };
}
