//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Dictionary.h"

#include "DictionaryValue.h"

namespace UrhoBackend {

Dictionary::Dictionary(Urho3D::Dictionary fromUrho) { dictionary_ = new Urho3D::Dictionary(); *dictionary_ = fromUrho; }
Dictionary::Dictionary(System::IntPtr^ ptr) : Dictionary(*((Urho3D::Dictionary*)ptr->ToPointer())) { }
Dictionary::~Dictionary() { delete dictionary_; }
bool Dictionary::empty::get() { return dictionary_->(); }
unsigned Dictionary::length::get() { return dictionary_->(); }
Dictionary^ Dictionary::&opAssign(Dictionary^ A)  { return  gcnew UrhoBackend::Dictionary(dictionary_->(*A->dictionary_)); }

void Dictionary::Set(System::String^ A, ? B)  {  dictionary_->(Urho3D::String(ToCString(A)), B); }

bool Dictionary::Get(System::String^ A, ?out B)  { return  dictionary_->(Urho3D::String(ToCString(A)), B); }

void Dictionary::Set(System::String^ A, int64 B)  {  dictionary_->(Urho3D::String(ToCString(A)), B); }

bool Dictionary::Get(System::String^ A, int64out B)  { return  dictionary_->(Urho3D::String(ToCString(A)), B); }

void Dictionary::Set(System::String^ A, double B)  {  dictionary_->(Urho3D::String(ToCString(A)), B); }

bool Dictionary::Get(System::String^ A, doubleout B)  { return  dictionary_->(Urho3D::String(ToCString(A)), B); }

bool Dictionary::Exists(System::String^ A)  { return  dictionary_->(Urho3D::String(ToCString(A))); }

void Dictionary::Erase(System::String^ A)  {  dictionary_->(Urho3D::String(ToCString(A))); }

void Dictionary::Clear()  {  dictionary_->(); }

Array<String> Dictionary::@get_keys()  { return  dictionary_->(); }

DictionaryValue^ Dictionary::&opIndex(System::String^ A)  { return  gcnew UrhoBackend::DictionaryValue(dictionary_->(Urho3D::String(ToCString(A)))); }

DictionaryValue^ Dictionary::&opIndex(System::String^ A)  { return  gcnew UrhoBackend::DictionaryValue(dictionary_->(Urho3D::String(ToCString(A)))); }

}
