//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Dictionary;
    class String;
    class DictionaryValue;
}

namespace UrhoBackend {

    ref class DictionaryValue;

    public ref class Dictionary {
    public:
        Dictionary(Urho3D::Dictionary comp);
        Dictionary(System::IntPtr^ ptr);
        ~Dictionary();

// Properties
        property bool empty { bool get(); }
        property unsigned length { unsigned get(); }
// Methods
        Dictionary^ &opAssign(Dictionary^);
        void Set(System::String^, ?);
        bool Get(System::String^, ?out);
        void Set(System::String^, int64);
        bool Get(System::String^, int64out);
        void Set(System::String^, double);
        bool Get(System::String^, doubleout);
        bool Exists(System::String^);
        void Erase(System::String^);
        void Clear();
        Array<String> @get_keys();
        DictionaryValue^ &opIndex(System::String^);
        DictionaryValue^ &opIndex(System::String^);
// Fields

        Urho3D::Dictionary* dictionary_;
    };
}
