//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class DictionaryValue;
}

namespace UrhoBackend {


    public ref class DictionaryValue {
    public:
        DictionaryValue(Urho3D::DictionaryValue comp);
        DictionaryValue(System::IntPtr^ ptr);
        ~DictionaryValue();

// Properties
// Methods
        DictionaryValue^ &opHndlAssign(?);
        DictionaryValue^ &opAssign(?);
        DictionaryValue^ &opAssign(double);
        DictionaryValue^ &opAssign(int64);
// Fields

        Urho3D::DictionaryValue* dictionaryvalue_;
    };
}
