//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Drawable;
    class Camera;
    class BoundingBox;
}



namespace UrhoBackend {

    ref class Camera;
    ref class BoundingBox;

    public ref class Drawable : public UrhoBackend::Component {
    public:
        Drawable(Urho3D::Drawable* comp);
        Drawable(System::IntPtr^ ptr);

// Properties
        property bool inView { bool get(); }
        property bool castShadows { bool get(); void set(bool); }
        property bool occluder { bool get(); void set(bool); }
        property bool occludee { bool get(); void set(bool); }
        property float drawDistance { float get(); void set(float); }
        property float shadowDistance { float get(); void set(float); }
        property float lodBias { float get(); void set(float); }
        property unsigned viewMask { unsigned get(); void set(unsigned); }
        property unsigned lightMask { unsigned get(); void set(unsigned); }
        property unsigned shadowMask { unsigned get(); void set(unsigned); }
        property unsigned zoneMask { unsigned get(); void set(unsigned); }
        property unsigned maxLights { unsigned get(); void set(unsigned); }
        property BoundingBox^ boundingBox { BoundingBox^ get(); }
        property BoundingBox^ worldBoundingBox { BoundingBox^ get(); }
// Methods
        bool IsInView(Camera^);
// Fields

        Urho3D::Drawable* drawable_;
    };
}
