//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class DropDownList;
    class UIElement;
    class Texture;
    class IntRect;
    class IntVector2;
    class ListView;
    class String;
}



namespace UrhoBackend {

    ref class UIElement;
    ref class Texture;
    ref class ListView;

    public ref class DropDownList : public UrhoBackend::UIElement {
    public:
        DropDownList(Urho3D::DropDownList* comp);
        DropDownList(System::IntPtr^ ptr);

// Properties
        property Texture^ texture { Texture^ get(); void set(Texture^); }
        property UrhoBackend::IntRect^ imageRect { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntRect^ border { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntRect^ imageBorder { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntVector2^ hoverOffset { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^); }
        property BlendMode blendMode { BlendMode get(); void set(BlendMode); }
        property bool tiled { bool get(); void set(bool); }
        property UrhoBackend::IntVector2^ pressedOffset { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^); }
        property UrhoBackend::IntVector2^ pressedChildOffset { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^); }
        property float repeatDelay { float get(); void set(float); }
        property float repeatRate { float get(); void set(float); }
        property bool pressed { bool get(); }
        property bool showPopup { bool get(); void set(bool); }
        property unsigned selection { unsigned get(); void set(unsigned); }
        property bool resizePopup { bool get(); void set(bool); }
        property int acceleratorKey { int get(); }
        property int acceleratorQualifiers { int get(); }
        property unsigned numItems { unsigned get(); }
        property UIElement^ items[unsigned] { UIElement^ get(unsigned); }
        property UIElement^ selectedItem { UIElement^ get(); }
        property ListView^ listView { ListView^ get(); }
        property UIElement^ placeholder { UIElement^ get(); void set(UIElement^); }
        property System::String^ placeholderText { System::String^ get(); }
// Methods
        void SetFullImageRect();
        void SetHoverOffset(int, int);
        void SetPressedOffset(int, int);
        void SetPressedChildOffset(int, int);
        void SetRepeat(float, float);
        void SetAccelerator(int, int);
        void AddItem(UIElement^);
        void InsertItem(unsigned, UIElement^);
        void RemoveItem(UIElement^);
        void RemoveItem(unsigned);
        void RemoveAllItems();
        UIElement^ getPopup();
// Fields

        Urho3D::DropDownList* dropdownlist_;
    };
}
