//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "DynamicNavigationMesh.h"

#include <Urho3D/Navigation/DynamicNavigationMesh.h>

namespace UrhoBackend {

DynamicNavigationMesh::DynamicNavigationMesh(Urho3D::DynamicNavigationMesh* fromUrho) : NavigationMesh(fromUrho) { dynamicnavigationmesh_ = fromUrho; }
DynamicNavigationMesh::DynamicNavigationMesh(System::IntPtr^ ptr) : DynamicNavigationMesh((Urho3D::DynamicNavigationMesh*)ptr->ToPointer()) { }

}
