//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class FileSystem;
    class String;
}



namespace UrhoBackend {


    public ref class FileSystem : public UrhoBackend::Object {
    public:
        FileSystem(Urho3D::FileSystem* comp);
        FileSystem(System::IntPtr^ ptr);

// Properties
        property System::String^ currentDir { System::String^ get(); void set(System::String^); }
        property bool executeConsoleCommands { bool get(); void set(bool); }
        property System::String^ programDir { System::String^ get(); }
        property System::String^ userDocumentsDir { System::String^ get(); }
// Methods
        bool FileExists(System::String^);
        bool DirExists(System::String^);
        bool SetLastModifiedTime(System::String^, unsigned);
        unsigned GetLastModifiedTime(System::String^);
        bool CreateDir(System::String^);
        int SystemCommand(System::String^, bool);
        unsigned SystemCommandAsync(System::String^);
        bool SystemOpen(System::String^, System::String^);
        bool Copy(System::String^, System::String^);
        bool Rename(System::String^, System::String^);
        bool Delete(System::String^);
        System::String^ GetAppPreferencesDir(String org, String app);
// Fields

        Urho3D::FileSystem* filesystem_;
    };
}
