//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class FocusParameters;
}

#include <Urho3D/Graphics/Light.h>

namespace UrhoBackend {


    public ref class FocusParameters {
    public:
        FocusParameters(Urho3D::FocusParameters comp);
        FocusParameters(System::IntPtr^ ptr);
        ~FocusParameters();

// Properties
// Methods
// Fields
        property bool focus { bool get(); void set(bool value); }
        property bool nonUniform { bool get(); void set(bool value); }
        property bool autoSize { bool get(); void set(bool value); }
        property float quantize { float get(); void set(float value); }
        property float minView { float get(); void set(float value); }

        Urho3D::FocusParameters* focusparameters_;
    };
}
