//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Font.h"

#include <Urho3D/UI/Font.h>
#include <Urho3D/IO/File.h>
#include "File.h"

namespace UrhoBackend {

Font::Font(Urho3D::Font* fromUrho) : Resource(fromUrho) { font_ = fromUrho; }
Font::Font(System::IntPtr^ ptr) : Font((Urho3D::Font*)ptr->ToPointer()) { }

UrhoBackend::IntVector2^ Font::absoluteGlyphOffset::get() { return gcnew UrhoBackend::IntVector2(font_->GetAbsoluteGlyphOffset()); }
void Font::absoluteGlyphOffset::set(UrhoBackend::IntVector2^ value) { font_->SetAbsoluteGlyphOffset(value->ToIntVector2()); }

UrhoBackend::Vector2^ Font::scaledGlyphOffset::get() { return gcnew UrhoBackend::Vector2(font_->GetScaledGlyphOffset()); }
void Font::scaledGlyphOffset::set(UrhoBackend::Vector2^ value) { font_->SetScaledGlyphOffset(value->ToVector2()); }

bool Font::SaveXML(File^ A, int B, bool usedGlyphs, System::String^ indentation)  { return  font_->SaveXML(A->file_, B, usedGlyphs, Urho3D::String(ToCString(indentation))); }

UrhoBackend::IntVector2^ Font::GetTotalGlyphOffset(int A)  { return  gcnew UrhoBackend::IntVector2(font_->GetTotalGlyphOffset(A)); }

}
