//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

namespace Urho3D {
    class Image;
    class Color;
    class String;
    class IntRect;
}

#include "Resource.h"

namespace UrhoBackend {


    public ref class Image : public UrhoBackend::Resource {
    public:
        Image(Urho3D::Image* comp);
        Image(System::IntPtr^ ptr);

// Properties
        property int width { int get(); }
        property int height { int get(); }
        property int depth { int get(); }
        property unsigned components { unsigned get(); }
        property bool compressed { bool get(); }
        property CompressedFormat compressedFormat { CompressedFormat get(); }
        property unsigned numCompressedLevels { unsigned get(); }
// Methods
        bool SetSize(int, int, unsigned);
        bool SetSize(int, int, int, unsigned);
        void SetPixel(int, int, UrhoBackend::Color^);
        void SetPixel(int, int, int, UrhoBackend::Color^);
        void SetPixelInt(int, int, unsigned);
        void SetPixelInt(int, int, int, unsigned);
        bool FlipHorizontal();
        bool FlipVertical();
        bool Resize(int, int);
        void Clear(UrhoBackend::Color^);
        void ClearInt(unsigned);
        void SaveBMP(System::String^);
        void SavePNG(System::String^);
        void SaveTGA(System::String^);
        void SaveJPG(System::String^, int);
        UrhoBackend::Color^ GetPixel(int, int);
        UrhoBackend::Color^ GetPixel(int, int, int);
        unsigned GetPixelInt(int, int);
        unsigned GetPixelInt(int, int, int);
        UrhoBackend::Color^ GetPixelBilinear(float, float);
        UrhoBackend::Color^ GetPixelTrilinear(float, float, float);
        Image^ GetSubimage(UrhoBackend::IntRect^);
// Fields

        Urho3D::Image* image_;
    };
}
