//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class JoystickState;
    class String;
}

#include <Urho3D/Input/Input.h>

namespace UrhoBackend {


    public ref class JoystickState {
    public:
        JoystickState(Urho3D::JoystickState comp);
        JoystickState(System::IntPtr^ ptr);
        ~JoystickState();

// Properties
        property bool controller { bool get(); }
        property unsigned numButtons { unsigned get(); }
        property unsigned numAxes { unsigned get(); }
        property unsigned numHats { unsigned get(); }
        property bool buttonDown[unsigned] { bool get(unsigned); }
        property bool buttonPress[unsigned] { bool get(unsigned); }
        property float axisPosition[unsigned] { float get(unsigned); }
        property int hatPosition[unsigned] { int get(unsigned); }
// Methods
// Fields
        property System::String^ name { System::String^ get(); void set(System::String^ value); }
        property int joystickID { int get(); void set(int value); }

        Urho3D::JoystickState* joystickstate_;
    };
}
