//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Log;
    class String;
}



namespace UrhoBackend {


    public ref class Log : public UrhoBackend::Object {
    public:
        Log(Urho3D::Log* comp);
        Log(System::IntPtr^ ptr);

// Properties
        property int level { int get(); void set(int); }
        property bool timeStamp { bool get(); void set(bool); }
        property System::String^ lastMessage { System::String^ get(); }
        property bool quiet { bool get(); void set(bool); }
// Methods
        void Open(System::String^);
        void Close();
// Fields

        Urho3D::Log* log_;
    };
}
