//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class MessageBox;
    class String;
    class UIElement;
}



namespace UrhoBackend {

    ref class UIElement;

    public ref class MessageBox : public UrhoBackend::Object {
    public:
        MessageBox(Urho3D::MessageBox* comp);
        MessageBox(System::IntPtr^ ptr);

// Properties
        property System::String^ title { System::String^ get(); void set(System::String^); }
        property System::String^ message { System::String^ get(); void set(System::String^); }
        property UIElement^ window { UIElement^ get(); }
// Methods
// Fields

        Urho3D::MessageBox* messagebox_;
    };
}
