//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Model;
    class Geometry;
    class BoundingBox;
    class Skeleton;
    class Vector3;
}

#include "Resource.h"

namespace UrhoBackend {

    ref class Geometry;
    ref class BoundingBox;
    ref class Skeleton;

    public ref class Model : public UrhoBackend::Resource {
    public:
        Model(Urho3D::Model* comp);
        Model(System::IntPtr^ ptr);

// Properties
        property BoundingBox^ boundingBox { BoundingBox^ get(); void set(BoundingBox^); }
        property Skeleton^ skeleton { Skeleton^ get(); }
        property unsigned numGeometries { unsigned get(); void set(unsigned); }
        property unsigned numGeometryLodLevels[unsigned] { unsigned get(unsigned); void set(unsigned, unsigned); }
        property UrhoBackend::Vector3^ geometryCenters[unsigned] { UrhoBackend::Vector3^ get(unsigned); void set(unsigned, UrhoBackend::Vector3^); }
        property unsigned numMorphs { unsigned get(); }
// Methods
        bool SetGeometry(unsigned, unsigned, Geometry^);
        Geometry^ GetGeometry(unsigned, unsigned);
// Fields

        Urho3D::Model* model_;
    };
}
