//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class NavArea;
    class BoundingBox;
}



namespace UrhoBackend {

    ref class BoundingBox;

    public ref class NavArea : public UrhoBackend::Component {
    public:
        NavArea(Urho3D::NavArea* comp);
        NavArea(System::IntPtr^ ptr);

// Properties
        property BoundingBox^ boundingBox { BoundingBox^ get(); void set(BoundingBox^); }
        property unsigned areaID { unsigned get(); void set(unsigned); }
        property BoundingBox^ worldBoundingBox { BoundingBox^ get(); }
// Methods
// Fields

        Urho3D::NavArea* navarea_;
    };
}
