//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "NavArea.h"

#include <Urho3D/Navigation/NavArea.h>
#include <Urho3D/Math/BoundingBox.h>
#include "BoundingBox.h"

namespace UrhoBackend {

NavArea::NavArea(Urho3D::NavArea* fromUrho) : Component(fromUrho) { navarea_ = fromUrho; }
NavArea::NavArea(System::IntPtr^ ptr) : NavArea((Urho3D::NavArea*)ptr->ToPointer()) { }

BoundingBox^ NavArea::boundingBox::get() { return gcnew UrhoBackend::BoundingBox(navarea_->GetBoundingBox()); }
void NavArea::boundingBox::set(BoundingBox^ value) { navarea_->SetBoundingBox(*value->boundingbox_); }

unsigned NavArea::areaID::get() { return navarea_->GetAreaID(); }
void NavArea::areaID::set(unsigned value) { navarea_->SetAreaID(value); }

BoundingBox^ NavArea::worldBoundingBox::get() { return gcnew UrhoBackend::BoundingBox(navarea_->GetWorldBoundingBox()); }
}
