//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Navigable;
}



namespace UrhoBackend {


    public ref class Navigable : public UrhoBackend::Component {
    public:
        Navigable(Urho3D::Navigable* comp);
        Navigable(System::IntPtr^ ptr);

// Properties
        property bool recursive { bool get(); void set(bool); }
// Methods
// Fields

        Urho3D::Navigable* navigable_;
    };
}
