//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Navigable.h"

#include <Urho3D/Navigation/Navigable.h>

namespace UrhoBackend {

Navigable::Navigable(Urho3D::Navigable* fromUrho) : Component(fromUrho) { navigable_ = fromUrho; }
Navigable::Navigable(System::IntPtr^ ptr) : Navigable((Urho3D::Navigable*)ptr->ToPointer()) { }

bool Navigable::recursive::get() { return navigable_->IsRecursive(); }
void Navigable::recursive::set(bool value) { navigable_->SetRecursive(value); }

}
