//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class NetworkPriority;
}



namespace UrhoBackend {


    public ref class NetworkPriority : public UrhoBackend::Component {
    public:
        NetworkPriority(Urho3D::NetworkPriority* comp);
        NetworkPriority(System::IntPtr^ ptr);

// Properties
        property float basePriority { float get(); void set(float); }
        property float distanceFactor { float get(); void set(float); }
        property float minPriority { float get(); void set(float); }
        property bool alwaysUpdateOwner { bool get(); void set(bool); }
// Methods
// Fields

        Urho3D::NetworkPriority* networkpriority_;
    };
}
