//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "NetworkPriority.h"

#include <Urho3D/Network/NetworkPriority.h>

namespace UrhoBackend {

NetworkPriority::NetworkPriority(Urho3D::NetworkPriority* fromUrho) : Component(fromUrho) { networkpriority_ = fromUrho; }
NetworkPriority::NetworkPriority(System::IntPtr^ ptr) : NetworkPriority((Urho3D::NetworkPriority*)ptr->ToPointer()) { }

float NetworkPriority::basePriority::get() { return networkpriority_->GetBasePriority(); }
void NetworkPriority::basePriority::set(float value) { networkpriority_->SetBasePriority(value); }

float NetworkPriority::distanceFactor::get() { return networkpriority_->GetDistanceFactor(); }
void NetworkPriority::distanceFactor::set(float value) { networkpriority_->SetDistanceFactor(value); }

float NetworkPriority::minPriority::get() { return networkpriority_->GetMinPriority(); }
void NetworkPriority::minPriority::set(float value) { networkpriority_->SetMinPriority(value); }

bool NetworkPriority::alwaysUpdateOwner::get() { return networkpriority_->GetAlwaysUpdateOwner(); }
void NetworkPriority::alwaysUpdateOwner::set(bool value) { networkpriority_->SetAlwaysUpdateOwner(value); }

}
