//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Object;
    class StringHash;
    class String;
}



namespace UrhoBackend {


    public ref class Object : public UrhoBackend::RefCounted {
    public:
        Object(Urho3D::Object* comp);
        Object(System::IntPtr^ ptr);

// Properties
        property UrhoBackend::StringHash^ type { UrhoBackend::StringHash^ get(); }
        property UrhoBackend::StringHash^ baseType { UrhoBackend::StringHash^ get(); }
        property System::String^ typeName { System::String^ get(); }
        property System::String^ category { System::String^ get(); }
// Methods
// Fields

        Urho3D::Object* object_;
    };
}
