//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "ObjectAnimation.h"

#include <Urho3D/Scene/ObjectAnimation.h>
#include <Urho3D/Scene/ValueAnimation.h>
#include "ValueAnimation.h"
#include <Urho3D/Scene/AnimationDefs.h>

namespace UrhoBackend {

ObjectAnimation::ObjectAnimation(Urho3D::ObjectAnimation* fromUrho) : UObject(fromUrho) { objectanimation_ = fromUrho; }
ObjectAnimation::ObjectAnimation(System::IntPtr^ ptr) : ObjectAnimation((Urho3D::ObjectAnimation*)ptr->ToPointer()) { }

Variant^ ObjectAnimation::attributeAnimations::get(System::String^ A) { return gcnew UrhoBackend::Variant(objectanimation_->GetAttributeAnimation(Urho3D::String(ToCString(A)))); }

Variant^ ObjectAnimation::wrapModes::get(System::String^ A) { return gcnew UrhoBackend::Variant(objectanimation_->GetAttributeAnimationWrapMode(Urho3D::String(ToCString(A)))); }

Variant^ ObjectAnimation::speeds::get(System::String^ A) { return gcnew UrhoBackend::Variant(objectanimation_->GetAttributeAnimationSpeed(Urho3D::String(ToCString(A)))); }

void ObjectAnimation::AddAttributeAnimation(System::String^ A, ValueAnimation^ B, WrapMode wrapMod, float spee)  {  objectanimation_->AddAttributeAnimation(Urho3D::String(ToCString(A)), B->valueanimation_, (Urho3D::WrapMode)wrapMod, spee); }

void ObjectAnimation::RemoveAttributeAnimation(System::String^ A)  {  objectanimation_->RemoveAttributeAnimation(Urho3D::String(ToCString(A))); }

void ObjectAnimation::RemoveAttributeAnimation(ValueAnimation^ A)  {  objectanimation_->RemoveAttributeAnimation(A->valueanimation_); }

ValueAnimation^ ObjectAnimation::GetAttributeAnimation(System::String^ A)  { return  gcnew UrhoBackend::ValueAnimation(objectanimation_->GetAttributeAnimation(Urho3D::String(ToCString(A)))); }

WrapMode ObjectAnimation::GetAttributeAnimationWrapMode(System::String^ A)  { return  (UrhoBackend::WrapMode)objectanimation_->GetAttributeAnimationWrapMode(Urho3D::String(ToCString(A))); }

float ObjectAnimation::GetAttributeAnimationSpeed(System::String^ A)  { return  objectanimation_->GetAttributeAnimationSpeed(Urho3D::String(ToCString(A))); }

}
