//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Obstacle;
}



namespace UrhoBackend {


    public ref class Obstacle : public UrhoBackend::Component {
    public:
        Obstacle(Urho3D::Obstacle* comp);
        Obstacle(System::IntPtr^ ptr);

// Properties
        property float radius { float get(); void set(float); }
        property float height { float get(); void set(float); }
        property unsigned obstacleId { unsigned get(); }
// Methods
// Fields

        Urho3D::Obstacle* obstacle_;
    };
}
