//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Obstacle.h"

#include <Urho3D/Navigation/Obstacle.h>

namespace UrhoBackend {

Obstacle::Obstacle(Urho3D::Obstacle* fromUrho) : Component(fromUrho) { obstacle_ = fromUrho; }
Obstacle::Obstacle(System::IntPtr^ ptr) : Obstacle((Urho3D::Obstacle*)ptr->ToPointer()) { }

float Obstacle::radius::get() { return obstacle_->GetRadius(); }
void Obstacle::radius::set(float value) { obstacle_->SetRadius(value); }

float Obstacle::height::get() { return obstacle_->GetHeight(); }
void Obstacle::height::set(float value) { obstacle_->SetHeight(value); }

unsigned Obstacle::obstacleId::get() { return obstacle_->GetObstacleID(); }
}
