//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Octree;
    class BoundingBox;
    class Drawable;
}



namespace UrhoBackend {

    ref class BoundingBox;
    ref class Drawable;

    public ref class Octree : public UrhoBackend::Component {
    public:
        Octree(Urho3D::Octree* comp);
        Octree(System::IntPtr^ ptr);

// Properties
        property BoundingBox^ worldBoundingBox { BoundingBox^ get(); }
        property unsigned numLevels { unsigned get(); }
// Methods
        void SetSize(BoundingBox^, unsigned);
        void AddManualDrawable(Drawable^);
        void RemoveManualDrawable(Drawable^);
// Fields

        Urho3D::Octree* octree_;
    };
}
