//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "OffMeshConnection.h"

#include <Urho3D/Navigation/OffMeshConnection.h>

namespace UrhoBackend {

OffMeshConnection::OffMeshConnection(Urho3D::OffMeshConnection* fromUrho) : Component(fromUrho) { offmeshconnection_ = fromUrho; }
OffMeshConnection::OffMeshConnection(System::IntPtr^ ptr) : OffMeshConnection((Urho3D::OffMeshConnection*)ptr->ToPointer()) { }

void OffMeshConnection::bidirectional::set(bool value) { offmeshconnection_->SetBidirectional(value); }

Node^ OffMeshConnection::endPoint::get() { return gcnew UrhoBackend::Node(offmeshconnection_->GetEndPoint()); }
void OffMeshConnection::endPoint::set(Node^ value) { offmeshconnection_->SetEndPoint(value->node_); }

float OffMeshConnection::radius::get() { return offmeshconnection_->GetRadius(); }
void OffMeshConnection::radius::set(float value) { offmeshconnection_->SetRadius(value); }

bool OffMeshConnection::bidirectional::get() { return offmeshconnection_->IsBidirectional(); }
}
