//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "ParticleEffect2D.h"

#include <Urho3D/Urho2D/ParticleEffect2D.h>

namespace UrhoBackend {

ParticleEffect2D::ParticleEffect2D(Urho3D::ParticleEffect2D* fromUrho) : Resource(fromUrho) { particleeffect2d_ = fromUrho; }
ParticleEffect2D::ParticleEffect2D(System::IntPtr^ ptr) : ParticleEffect2D((Urho3D::ParticleEffect2D*)ptr->ToPointer()) { }

}
