//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Pass;
    class String;
}



namespace UrhoBackend {


    public ref class Pass : public UrhoBackend::RefCounted {
    public:
        Pass(Urho3D::Pass* comp);
        Pass(System::IntPtr^ ptr);

// Properties
        property BlendMode blendMode { BlendMode get(); void set(BlendMode); }
        property CompareMode depthTestMode { CompareMode get(); void set(CompareMode); }
        property PassLightingMode lightingMode { PassLightingMode get(); void set(PassLightingMode); }
        property bool depthWrite { bool get(); void set(bool); }
        property bool alphaMask { bool get(); void set(bool); }
        property bool desktop { bool get(); void set(bool); }
        property System::String^ vertexShader { System::String^ get(); void set(System::String^); }
        property System::String^ pixelShader { System::String^ get(); void set(System::String^); }
        property System::String^ vertexShaderDefines { System::String^ get(); void set(System::String^); }
        property System::String^ pixelShaderDefines { System::String^ get(); void set(System::String^); }
// Methods
// Fields

        Urho3D::Pass* pass_;
    };
}
