//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class PhysicsRaycastResult2D;
    class Vector2;
}

#include <Urho3D/Urho2D/PhysicsWorld2D.h>

namespace UrhoBackend {


    public ref class PhysicsRaycastResult2D {
    public:
        PhysicsRaycastResult2D(Urho3D::PhysicsRaycastResult2D comp);
        PhysicsRaycastResult2D(System::IntPtr^ ptr);
        ~PhysicsRaycastResult2D();

// Properties
// Methods
        PhysicsRaycastResult2D^ opAssign(PhysicsRaycastResult2D^);
// Fields
        property UrhoBackend::Vector2^ position { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^ value); }
        property UrhoBackend::Vector2^ normal { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^ value); }
        property float distance { float get(); void set(float value); }

        Urho3D::PhysicsRaycastResult2D* physicsraycastresult2d_;
    };
}
