//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "PhysicsRaycastResult2D.h"

#include <Urho3D/Urho2D/PhysicsWorld2D.h>

namespace UrhoBackend {

PhysicsRaycastResult2D::PhysicsRaycastResult2D(Urho3D::PhysicsRaycastResult2D fromUrho) { physicsraycastresult2d_ = new Urho3D::PhysicsRaycastResult2D(); *physicsraycastresult2d_ = fromUrho; }
PhysicsRaycastResult2D::PhysicsRaycastResult2D(System::IntPtr^ ptr) : PhysicsRaycastResult2D(*((Urho3D::PhysicsRaycastResult2D*)ptr->ToPointer())) { }
PhysicsRaycastResult2D::~PhysicsRaycastResult2D() { delete physicsraycastresult2d_; }
PhysicsRaycastResult2D^ PhysicsRaycastResult2D::opAssign(PhysicsRaycastResult2D^ A)  { return  gcnew UrhoBackend::PhysicsRaycastResult2D(physicsraycastresult2d_->operator =(*A->physicsraycastresult2d_)); }

UrhoBackend::Vector2^ PhysicsRaycastResult2D::position::get() { return gcnew UrhoBackend::Vector2(physicsraycastresult2d_->position_); }
void PhysicsRaycastResult2D::position::set(UrhoBackend::Vector2^ value) { physicsraycastresult2d_->position_ = value->ToVector2(); }

UrhoBackend::Vector2^ PhysicsRaycastResult2D::normal::get() { return gcnew UrhoBackend::Vector2(physicsraycastresult2d_->normal_); }
void PhysicsRaycastResult2D::normal::set(UrhoBackend::Vector2^ value) { physicsraycastresult2d_->normal_ = value->ToVector2(); }

float PhysicsRaycastResult2D::distance::get() { return physicsraycastresult2d_->distance_; }
void PhysicsRaycastResult2D::distance::set(float value) { physicsraycastresult2d_->distance_ = value; }

}
