//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class PhysicsRaycastResult;
    class Vector3;
}

#include <Urho3D/Physics/PhysicsWorld.h>

namespace UrhoBackend {


    public ref class PhysicsRaycastResult {
    public:
        PhysicsRaycastResult(Urho3D::PhysicsRaycastResult comp);
        PhysicsRaycastResult(System::IntPtr^ ptr);
        ~PhysicsRaycastResult();

// Properties
// Methods
        PhysicsRaycastResult^ opAssign(PhysicsRaycastResult^);
// Fields
        property UrhoBackend::Vector3^ position { UrhoBackend::Vector3^ get(); void set(UrhoBackend::Vector3^ value); }
        property UrhoBackend::Vector3^ normal { UrhoBackend::Vector3^ get(); void set(UrhoBackend::Vector3^ value); }
        property float distance { float get(); void set(float value); }

        Urho3D::PhysicsRaycastResult* physicsraycastresult_;
    };
}
