//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "PhysicsRaycastResult.h"

#include <Urho3D/Physics/PhysicsWorld.h>

namespace UrhoBackend {

PhysicsRaycastResult::PhysicsRaycastResult(Urho3D::PhysicsRaycastResult fromUrho) { physicsraycastresult_ = new Urho3D::PhysicsRaycastResult(); *physicsraycastresult_ = fromUrho; }
PhysicsRaycastResult::PhysicsRaycastResult(System::IntPtr^ ptr) : PhysicsRaycastResult(*((Urho3D::PhysicsRaycastResult*)ptr->ToPointer())) { }
PhysicsRaycastResult::~PhysicsRaycastResult() { delete physicsraycastresult_; }
PhysicsRaycastResult^ PhysicsRaycastResult::opAssign(PhysicsRaycastResult^ A)  { return  gcnew UrhoBackend::PhysicsRaycastResult(physicsraycastresult_->operator =(*A->physicsraycastresult_)); }

UrhoBackend::Vector3^ PhysicsRaycastResult::position::get() { return gcnew UrhoBackend::Vector3(physicsraycastresult_->position_); }
void PhysicsRaycastResult::position::set(UrhoBackend::Vector3^ value) { physicsraycastresult_->position_ = value->ToVector3(); }

UrhoBackend::Vector3^ PhysicsRaycastResult::normal::get() { return gcnew UrhoBackend::Vector3(physicsraycastresult_->normal_); }
void PhysicsRaycastResult::normal::set(UrhoBackend::Vector3^ value) { physicsraycastresult_->normal_ = value->ToVector3(); }

float PhysicsRaycastResult::distance::get() { return physicsraycastresult_->distance_; }
void PhysicsRaycastResult::distance::set(float value) { physicsraycastresult_->distance_ = value; }

}
