//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class PropertySet2D;
    class String;
}



namespace UrhoBackend {


    public ref class PropertySet2D : public UrhoBackend::RefCounted {
    public:
        PropertySet2D(Urho3D::PropertySet2D* comp);
        PropertySet2D(System::IntPtr^ ptr);

// Properties
// Methods
        bool HasProperty(System::String^);
        System::String^ GetProperty(System::String^);
// Fields

        Urho3D::PropertySet2D* propertyset2d_;
    };
}
