//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "PropertySet2D.h"

#include <Urho3D/Urho2D/TileMapDefs2D.h>

namespace UrhoBackend {

PropertySet2D::PropertySet2D(Urho3D::PropertySet2D* fromUrho) : RefCounted(fromUrho) { propertyset2d_ = fromUrho; }
PropertySet2D::PropertySet2D(System::IntPtr^ ptr) : PropertySet2D((Urho3D::PropertySet2D*)ptr->ToPointer()) { }

bool PropertySet2D::HasProperty(System::String^ A)  { return  propertyset2d_->HasProperty(Urho3D::String(ToCString(A))); }

System::String^ PropertySet2D::GetProperty(System::String^ A)  { return  gcnew System::String(propertyset2d_->HasProperty(Urho3D::String(ToCString(A))).CString()); }

}
