//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Ray;
    class Vector3;
    class Plane;
    class Sphere;
    class BoundingBox;
    class Frustum;
    class Matrix3x4;
}

#include <Urho3D/Math/Ray.h>

namespace UrhoBackend {

    ref class Plane;
    ref class Sphere;
    ref class BoundingBox;
    ref class Frustum;

    public ref class Ray {
    public:
        Ray(Urho3D::Ray comp);
        Ray(System::IntPtr^ ptr);
        ~Ray();

// Properties
// Methods
        Ray^ opAssign(Ray^);
        bool opEquals(Ray^);
        void Define(UrhoBackend::Vector3^, UrhoBackend::Vector3^);
        UrhoBackend::Vector3^ Project(UrhoBackend::Vector3^);
        float Distance(UrhoBackend::Vector3^);
        UrhoBackend::Vector3^ ClosestPoint(Ray^);
        float HitDistance(Plane^);
        float HitDistance(Sphere^);
        float HitDistance(BoundingBox^);
        float HitDistance(Frustum^, bool);
        float HitDistance(UrhoBackend::Vector3^, UrhoBackend::Vector3^, UrhoBackend::Vector3^);
        Ray^ Transformed(UrhoBackend::Matrix3x4^);
// Fields
        property UrhoBackend::Vector3^ origin { UrhoBackend::Vector3^ get(); void set(UrhoBackend::Vector3^ value); }
        property UrhoBackend::Vector3^ direction { UrhoBackend::Vector3^ get(); void set(UrhoBackend::Vector3^ value); }

        Urho3D::Ray* ray_;
    };
}
