//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "RayQueryResult.h"

#include <Urho3D/Graphics/OctreeQuery.h>

namespace UrhoBackend {

RayQueryResult::RayQueryResult(Urho3D::RayQueryResult fromUrho) { rayqueryresult_ = new Urho3D::RayQueryResult(); *rayqueryresult_ = fromUrho; }
RayQueryResult::RayQueryResult(System::IntPtr^ ptr) : RayQueryResult(*((Urho3D::RayQueryResult*)ptr->ToPointer())) { }
RayQueryResult::~RayQueryResult() { delete rayqueryresult_; }
UrhoBackend::Vector3^ RayQueryResult::position::get() { return gcnew UrhoBackend::Vector3(rayqueryresult_->position_); }
void RayQueryResult::position::set(UrhoBackend::Vector3^ value) { rayqueryresult_->position_ = value->ToVector3(); }

UrhoBackend::Vector3^ RayQueryResult::normal::get() { return gcnew UrhoBackend::Vector3(rayqueryresult_->normal_); }
void RayQueryResult::normal::set(UrhoBackend::Vector3^ value) { rayqueryresult_->normal_ = value->ToVector3(); }

float RayQueryResult::distance::get() { return rayqueryresult_->distance_; }
void RayQueryResult::distance::set(float value) { rayqueryresult_->distance_ = value; }

unsigned RayQueryResult::subObject::get() { return rayqueryresult_->subObject_; }
void RayQueryResult::subObject::set(unsigned value) { rayqueryresult_->subObject_ = value; }

}
