//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "RefCounted.h"

#include <Urho3D/Container/RefCounted.h>

namespace UrhoBackend {

RefCounted::RefCounted(Urho3D::RefCounted fromUrho) { refcounted_ = new Urho3D::RefCounted(); *refcounted_ = fromUrho; }
RefCounted::RefCounted(System::IntPtr^ ptr) : RefCounted(*((Urho3D::RefCounted*)ptr->ToPointer())) { }
RefCounted::~RefCounted() { delete refcounted_; }
int RefCounted::refs::get() { return refcounted_->Refs(); }
int RefCounted::weakRefs::get() { return refcounted_->WeakRefs(); }
}
