//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class RefCounted;
}

#include <Urho3D/Container/RefCounted.h>

namespace UrhoBackend {


    public ref class RefCounted {
    public:
        RefCounted(Urho3D::RefCounted comp);
        RefCounted(System::IntPtr^ ptr);
        ~RefCounted();

// Properties
        property int refs { int get(); }
        property int weakRefs { int get(); }
// Methods
// Fields

        Urho3D::RefCounted* refcounted_;
    };
}
