//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class RenderSurface;
    class Texture;
    class Viewport;
}

#include <Urho3D/Graphics/RenderSurface.h>

namespace UrhoBackend {

    ref class Texture;
    ref class Viewport;

    public ref class RenderSurface {
    public:
        RenderSurface(Urho3D::RenderSurface* comp);
        RenderSurface(System::IntPtr^ ptr);
        ~RenderSurface();

// Properties
        property Texture^ parentTexture { Texture^ get(); }
        property int width { int get(); }
        property int height { int get(); }
        property TextureUsage usage { TextureUsage get(); }
        property unsigned numViewports { unsigned get(); void set(unsigned); }
        property Viewport^ viewports[unsigned] { Viewport^ get(unsigned); void set(unsigned, Viewport^); }
        property RenderSurfaceUpdateMode updateMode { RenderSurfaceUpdateMode get(); void set(RenderSurfaceUpdateMode); }
        property RenderSurface^ linkedRenderTarget { RenderSurface^ get(); void set(RenderSurface^); }
        property RenderSurface^ linkedDepthStencil { RenderSurface^ get(); void set(RenderSurface^); }
// Methods
        void QueueUpdate();
// Fields

        Urho3D::RenderSurface* rendersurface_;
    };
}
