//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class RenderPath;
    class XMLFile;
    class String;
    class RenderTargetInfo;
    class RenderPathCommand;
    class Variant;
}



namespace UrhoBackend {

    ref class XMLFile;
    ref class RenderTargetInfo;
    ref class RenderPathCommand;

    public ref class RenderPath : public UrhoBackend::RefCounted {
    public:
        RenderPath(Urho3D::RenderPath* comp);
        RenderPath(System::IntPtr^ ptr);

// Properties
        property unsigned numRenderTargets { unsigned get(); }
        property void renderTargets[unsigned, RenderTargetInfo^] { void set(unsigned, RenderTargetInfo^, void); }
        property unsigned numCommands { unsigned get(); }
        property void commands[unsigned, RenderPathCommand^] { void set(unsigned, RenderPathCommand^, void); }
        property Variant^ shaderParameters[System::String^] { Variant^ get(System::String^); void set(System::String^, Variant^); }
// Methods
        bool Load(XMLFile^);
        bool Append(XMLFile^);
        void SetEnabled(System::String^, bool);
        void ToggleEnabled(System::String^);
        void AddRenderTarget(RenderTargetInfo^);
        void RemoveRenderTarget(unsigned);
        void RemoveRenderTarget(System::String^);
        void RemoveRenderTargts(System::String^);
        void AddCommand(RenderPathCommand^);
        void InsertCommand(unsigned, RenderPathCommand^);
        void RemoveCommand(unsigned);
        void RemoveCommands(System::String^);
// Fields

        Urho3D::RenderPath* renderpath_;
    };
}
