//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class RenderTargetInfo;
    class String;
    class Vector2;
}

#include <Urho3D/Graphics/RenderPath.h>

namespace UrhoBackend {


    public ref class RenderTargetInfo {
    public:
        RenderTargetInfo(Urho3D::RenderTargetInfo comp);
        RenderTargetInfo(System::IntPtr^ ptr);
        ~RenderTargetInfo();

// Properties
// Methods
        RenderTargetInfo^ opAssign(RenderTargetInfo^);
// Fields
        property System::String^ name { System::String^ get(); void set(System::String^ value); }
        property System::String^ tag { System::String^ get(); void set(System::String^ value); }
        property unsigned format { unsigned get(); void set(unsigned value); }
        property UrhoBackend::Vector2^ size { UrhoBackend::Vector2^ get(); void set(UrhoBackend::Vector2^ value); }
        property RenderTargetSizeMode sizeMode { RenderTargetSizeMode get(); void set(RenderTargetSizeMode value); }
        property bool enabled { bool get(); void set(bool value); }
        property bool cubemap { bool get(); void set(bool value); }
        property bool filtered { bool get(); void set(bool value); }
        property bool sRGB { bool get(); void set(bool value); }
        property bool persistent { bool get(); void set(bool value); }

        Urho3D::RenderTargetInfo* rendertargetinfo_;
    };
}
