//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Resource.h"

#include <Urho3D/Resource/Resource.h>

namespace UrhoBackend {

Resource::Resource(Urho3D::Resource* fromUrho) : UObject(fromUrho) { resource_ = fromUrho; }
Resource::Resource(System::IntPtr^ ptr) : Resource((Urho3D::Resource*)ptr->ToPointer()) { }

System::String^ Resource::name::get() { return gcnew System::String(resource_->GetName().CString()); }
void Resource::name::set(System::String^ value) { resource_->SetName(Urho3D::String(ToCString(value))); }

unsigned Resource::memoryUse::get() { return resource_->GetMemoryUse(); }
unsigned Resource::useTimer::get() { return resource_->GetUseTimer(); }
}
