//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class ResourceCache;
    class String;
    class PackageFile;
    class Resource;
    class StringHash;
}



namespace UrhoBackend {

    ref class PackageFile;
    ref class Resource;

    public ref class ResourceCache : public UrhoBackend::Object {
    public:
        ResourceCache(Urho3D::ResourceCache* comp);
        ResourceCache(System::IntPtr^ ptr);

// Properties
        property unsigned totalMemoryUse { unsigned get(); }
        property bool searchPackagesFirst { void set(bool); }
        property bool seachPackagesFirst { bool get(); }
        property bool autoReloadResources { bool get(); void set(bool); }
        property bool returnFailedResources { bool get(); void set(bool); }
        property int finishBackgroundResourcesMs { int get(); void set(int); }
        property unsigned numBackgroundLoadResources { unsigned get(); }
// Methods
        bool AddResourceDir(System::String^, unsigned);
        bool AddPackageFile(PackageFile^, unsigned);
        bool AddPackageFile(System::String^, unsigned);
        bool AddManualResource(Resource^);
        void RemoveResourceDir(System::String^);
        void RemovePackageFile(PackageFile^, bool, bool);
        void RemovePackageFile(System::String^, bool, bool);
        void ReleaseResources(UrhoBackend::StringHash^, bool);
        void ReleaseResources(System::String^, bool);
        void ReleaseAllResources(bool);
        bool ReloadResource(Resource^);
        void ReloadResourceWithDependencies(System::String^);
        bool Exists(System::String^);
        System::String^ GetPreferredResourceDir(System::String^);
        System::String^ SanitateResourceName(System::String^);
        System::String^ SanitateResourceDirName(System::String^);
        System::String^ GetResourceFileName(System::String^);
        Resource^ GetResource(UrhoBackend::StringHash^, System::String^, bool);
        Resource^ GetExistingResource(UrhoBackend::StringHash^, System::String^);
// Fields

        Urho3D::ResourceCache* resourcecache_;
    };
}
