//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Script.h"

#include <Urho3D/Script/Script.h>
#include <Urho3D/Script/ScriptFile.h>
#include "ScriptFile.h"
#include <Urho3D/Script/Script.h>

namespace UrhoBackend {

Script::Script(Urho3D::Script* fromUrho) : Object(fromUrho) { script_ = fromUrho; }
Script::Script(System::IntPtr^ ptr) : Script((Urho3D::Script*)ptr->ToPointer()) { }

ScriptFile^ Script::defaultScriptFile::get() { return gcnew UrhoBackend::ScriptFile(script_->GetDefaultScriptFile()); }
void Script::defaultScriptFile::set(ScriptFile^ value) { script_->SetDefaultScriptFile(value->scriptfile_); }

Scene^ Script::defaultScene::get() { return gcnew UrhoBackend::Scene(script_->GetDefaultScene()); }
void Script::defaultScene::set(Scene^ value) { script_->SetDefaultScene(value->scene_); }

bool Script::executeConsoleCommands::get() { return script_->GetExecuteConsoleCommands(); }
void Script::executeConsoleCommands::set(bool value) { script_->SetExecuteConsoleCommands(value); }

bool Script::Execute(System::String^ A)  { return  script_->Execute(Urho3D::String(ToCString(A))); }

void Script::DumpAPI(DumpMode mode, System::String^ sourceTree)  {  script_->DumpAPI((Urho3D::DumpMode)mode, Urho3D::String(ToCString(sourceTree))); }

}
