//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Script;
    class String;
    class ScriptFile;
    class Scene;
}



namespace UrhoBackend {

    ref class ScriptFile;

    public ref class Script : public UrhoBackend::Object {
    public:
        Script(Urho3D::Script* comp);
        Script(System::IntPtr^ ptr);

// Properties
        property ScriptFile^ defaultScriptFile { ScriptFile^ get(); void set(ScriptFile^); }
        property Scene^ defaultScene { Scene^ get(); void set(Scene^); }
        property bool executeConsoleCommands { bool get(); void set(bool); }
// Methods
        bool Execute(System::String^);
        void DumpAPI(DumpMode, System::String^);
// Fields

        Urho3D::Script* script_;
    };
}
