//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class ScriptFile;
    class String;
}

#include "Resource.h"

namespace UrhoBackend {


    public ref class ScriptFile : public UrhoBackend::Resource {
    public:
        ScriptFile(Urho3D::ScriptFile* comp);
        ScriptFile(System::IntPtr^ ptr);

// Properties
        property bool compiled { bool get(); }
// Methods
        void ClearDelayedExecute(System::String^);
// Fields

        Urho3D::ScriptFile* scriptfile_;
    };
}
