//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "ScrollBar.h"

#include <Urho3D/UI/ScrollBar.h>
#include <Urho3D/UI/Button.h>
#include "Button.h"
#include <Urho3D/UI/Slider.h>
#include "Slider.h"
#include <Urho3D/UI/UIElement.h>

namespace UrhoBackend {

ScrollBar::ScrollBar(Urho3D::ScrollBar* fromUrho) : UIElement(fromUrho) { scrollbar_ = fromUrho; }
ScrollBar::ScrollBar(System::IntPtr^ ptr) : ScrollBar((Urho3D::ScrollBar*)ptr->ToPointer()) { }

Orientation ScrollBar::orientation::get() { return (UrhoBackend::Orientation)scrollbar_->GetOrientation(); }
void ScrollBar::orientation::set(Orientation value) { scrollbar_->SetOrientation((Urho3D::Orientation)value); }

float ScrollBar::range::get() { return scrollbar_->GetRange(); }
void ScrollBar::range::set(float value) { scrollbar_->SetRange(value); }

float ScrollBar::value::get() { return scrollbar_->GetValue(); }
void ScrollBar::value::set(float value) { scrollbar_->SetValue(value); }

float ScrollBar::scrollStep::get() { return scrollbar_->GetScrollStep(); }
void ScrollBar::scrollStep::set(float value) { scrollbar_->SetScrollStep(value); }

float ScrollBar::stepFactor::get() { return scrollbar_->GetStepFactor(); }
void ScrollBar::stepFactor::set(bool value) { scrollbar_->SetStepFactor(value); }

float ScrollBar::effectiveScrollStep::get() { return scrollbar_->GetEffectiveScrollStep(); }
Button^ ScrollBar::backButton::get() { return gcnew UrhoBackend::Button(scrollbar_->GetBackButton()); }
Button^ ScrollBar::forwardButton::get() { return gcnew UrhoBackend::Button(scrollbar_->GetForwardButton()); }
Slider^ ScrollBar::slider::get() { return gcnew UrhoBackend::Slider(scrollbar_->GetSlider()); }
void ScrollBar::ChangeValue(float A)  {  scrollbar_->ChangeValue(A); }

void ScrollBar::StepBack()  {  scrollbar_->StepBack(); }

void ScrollBar::StepForward()  {  scrollbar_->StepForward(); }

}
