//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "ScrollView.h"

#include <Urho3D/UI/ScrollView.h>
#include <Urho3D/UI/UIElement.h>
#include "UIElement.h"
#include <Urho3D/UI/ScrollBar.h>
#include "ScrollBar.h"
#include <Urho3D/UI/BorderImage.h>
#include "BorderImage.h"

namespace UrhoBackend {

ScrollView::ScrollView(Urho3D::ScrollView* fromUrho) : UIElement(fromUrho) { scrollview_ = fromUrho; }
ScrollView::ScrollView(System::IntPtr^ ptr) : ScrollView((Urho3D::ScrollView*)ptr->ToPointer()) { }

UIElement^ ScrollView::contentElement::get() { return gcnew UrhoBackend::UIElement(scrollview_->GetContentElement()); }
void ScrollView::contentElement::set(UIElement^ value) { scrollview_->SetContentElement(value->uielement_); }

UrhoBackend::IntVector2^ ScrollView::viewPosition::get() { return gcnew UrhoBackend::IntVector2(scrollview_->GetViewPosition()); }
void ScrollView::viewPosition::set(UrhoBackend::IntVector2^ value) { scrollview_->SetViewPosition(value->ToIntVector2()); }

float ScrollView::scrollStep::get() { return scrollview_->GetScrollStep(); }
void ScrollView::scrollStep::set(float value) { scrollview_->SetScrollStep(value); }

float ScrollView::pageStep::get() { return scrollview_->GetPageStep(); }
void ScrollView::pageStep::set(float value) { scrollview_->SetPageStep(value); }

ScrollBar^ ScrollView::horizontalScrollBar::get() { return gcnew UrhoBackend::ScrollBar(scrollview_->GetHorizontalScrollBar()); }
ScrollBar^ ScrollView::verticalScrollBar::get() { return gcnew UrhoBackend::ScrollBar(scrollview_->GetVerticalScrollBar()); }
BorderImage^ ScrollView::scrollPanel::get() { return gcnew UrhoBackend::BorderImage(scrollview_->GetScrollPanel()); }
bool ScrollView::scrollBarsAutoVisible::get() { return scrollview_->GetScrollBarsAutoVisible(); }
void ScrollView::scrollBarsAutoVisible::set(bool value) { scrollview_->SetScrollBarsAutoVisible(value); }

float ScrollView::scrollDeceleration::get() { return scrollview_->GetScrollDeceleration(); }
void ScrollView::scrollDeceleration::set(float value) { scrollview_->SetScrollDeceleration(value); }

float ScrollView::scrollSnapEpsilon::get() { return scrollview_->GetScrollSnapEpsilon(); }
void ScrollView::scrollSnapEpsilon::set(float value) { scrollview_->SetScrollSnapEpsilon(value); }

bool ScrollView::autoDisableChildren::get() { return scrollview_->GetAutoDisableChildren(); }
void ScrollView::autoDisableChildren::set(bool value) { scrollview_->SetAutoDisableChildren(value); }

float ScrollView::autoDisableThreshold::get() { return scrollview_->GetAutoDisableThreshold(); }
void ScrollView::autoDisableThreshold::set(float value) { scrollview_->SetAutoDisableThreshold(value); }

void ScrollView::SetViewPosition(int A, int B)  {  scrollview_->SetViewPosition(A, B); }

void ScrollView::SetScrollBarsVisible(bool A, bool B)  {  scrollview_->SetScrollBarsVisible(A, B); }

}
