//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Skeleton;
    class Bone;
    class String;
}

#include <Urho3D/Graphics/Skeleton.h>

namespace UrhoBackend {

    ref class Bone;

    public ref class Skeleton {
    public:
        Skeleton(Urho3D::Skeleton comp);
        Skeleton(System::IntPtr^ ptr);
        ~Skeleton();

// Properties
        property Bone^ rootBone { Bone^ get(); }
        property unsigned numBones { unsigned get(); }
        property Bone^ bones[unsigned] { Bone^ get(unsigned); }
// Methods
        void Reset();
        Bone^ GetBone(System::String^);
// Fields

        Urho3D::Skeleton* skeleton_;
    };
}
