//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Skeleton.h"

#include <Urho3D/Graphics/Skeleton.h>
#include <Urho3D/Graphics/Skeleton.h>
#include "Bone.h"

namespace UrhoBackend {

Skeleton::Skeleton(Urho3D::Skeleton fromUrho) { skeleton_ = new Urho3D::Skeleton(); *skeleton_ = fromUrho; }
Skeleton::Skeleton(System::IntPtr^ ptr) : Skeleton(*((Urho3D::Skeleton*)ptr->ToPointer())) { }
Skeleton::~Skeleton() { delete skeleton_; }
Bone^ Skeleton::rootBone::get() { return gcnew UrhoBackend::Bone(skeleton_->GetRootBone()); }
unsigned Skeleton::numBones::get() { return skeleton_->GetNumBones(); }
Bone^ Skeleton::bones::get(unsigned A) { return gcnew UrhoBackend::Bone(skeleton_->GetBone(A)); }

void Skeleton::Reset()  {  skeleton_->Reset(); }

Bone^ Skeleton::GetBone(System::String^ A)  { return  gcnew UrhoBackend::Bone(skeleton_->GetBone(Urho3D::String(ToCString(A)))); }

}
