//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Skybox;
    class Zone;
}

#include "StaticModel.h"

namespace UrhoBackend {

    ref class Zone;

    public ref class Skybox : public UrhoBackend::StaticModel {
    public:
        Skybox(Urho3D::Skybox* comp);
        Skybox(System::IntPtr^ ptr);

// Properties
        property Zone^ zone { Zone^ get(); }
// Methods
// Fields

        Urho3D::Skybox* skybox_;
    };
}
