//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Slider;
    class Texture;
    class IntRect;
    class IntVector2;
    class BorderImage;
}



namespace UrhoBackend {

    ref class Texture;
    ref class BorderImage;

    public ref class Slider : public UrhoBackend::UIElement {
    public:
        Slider(Urho3D::Slider* comp);
        Slider(System::IntPtr^ ptr);

// Properties
        property Texture^ texture { Texture^ get(); void set(Texture^); }
        property UrhoBackend::IntRect^ imageRect { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntRect^ border { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntRect^ imageBorder { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property UrhoBackend::IntVector2^ hoverOffset { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^); }
        property BlendMode blendMode { BlendMode get(); void set(BlendMode); }
        property bool tiled { bool get(); void set(bool); }
        property Orientation orientation { Orientation get(); void set(Orientation); }
        property float range { float get(); void set(float); }
        property float value { float get(); void set(float); }
        property BorderImage^ knob { BorderImage^ get(); }
        property float repeatRate { float get(); void set(float); }
// Methods
        void SetFullImageRect();
        void SetHoverOffset(int, int);
        void ChangeValue(float);
// Fields

        Urho3D::Slider* slider_;
    };
}
