//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Slider.h"

#include <Urho3D/UI/Slider.h>
#include <Urho3D/Graphics/Texture.h>
#include "Texture.h"
#include <Urho3D/UI/BorderImage.h>
#include "BorderImage.h"
#include <Urho3D/Graphics/GraphicsDefs.h>
#include <Urho3D/UI/UIElement.h>

namespace UrhoBackend {

Slider::Slider(Urho3D::Slider* fromUrho) : UIElement(fromUrho) { slider_ = fromUrho; }
Slider::Slider(System::IntPtr^ ptr) : Slider((Urho3D::Slider*)ptr->ToPointer()) { }

Texture^ Slider::texture::get() { return gcnew UrhoBackend::Texture(slider_->GetTexture()); }
void Slider::texture::set(Texture^ value) { slider_->SetTexture(value->texture_); }

UrhoBackend::IntRect^ Slider::imageRect::get() { return gcnew UrhoBackend::IntRect(slider_->GetImageRect()); }
void Slider::imageRect::set(UrhoBackend::IntRect^ value) { slider_->SetImageRect(value->ToIntRect()); }

UrhoBackend::IntRect^ Slider::border::get() { return gcnew UrhoBackend::IntRect(slider_->GetBorder()); }
void Slider::border::set(UrhoBackend::IntRect^ value) { slider_->SetBorder(value->ToIntRect()); }

UrhoBackend::IntRect^ Slider::imageBorder::get() { return gcnew UrhoBackend::IntRect(slider_->GetImageBorder()); }
void Slider::imageBorder::set(UrhoBackend::IntRect^ value) { slider_->SetImageBorder(value->ToIntRect()); }

UrhoBackend::IntVector2^ Slider::hoverOffset::get() { return gcnew UrhoBackend::IntVector2(slider_->GetHoverOffset()); }
void Slider::hoverOffset::set(UrhoBackend::IntVector2^ value) { slider_->SetHoverOffset(value->ToIntVector2()); }

BlendMode Slider::blendMode::get() { return (UrhoBackend::BlendMode)slider_->GetBlendMode(); }
void Slider::blendMode::set(BlendMode value) { slider_->SetBlendMode((Urho3D::BlendMode)value); }

bool Slider::tiled::get() { return slider_->IsTiled(); }
void Slider::tiled::set(bool value) { slider_->SetTiled(value); }

Orientation Slider::orientation::get() { return (UrhoBackend::Orientation)slider_->GetOrientation(); }
void Slider::orientation::set(Orientation value) { slider_->SetOrientation((Urho3D::Orientation)value); }

float Slider::range::get() { return slider_->GetRange(); }
void Slider::range::set(float value) { slider_->SetRange(value); }

float Slider::value::get() { return slider_->GetValue(); }
void Slider::value::set(float value) { slider_->SetValue(value); }

BorderImage^ Slider::knob::get() { return gcnew UrhoBackend::BorderImage(slider_->GetKnob()); }
float Slider::repeatRate::get() { return slider_->GetRepeatRate(); }
void Slider::repeatRate::set(float value) { slider_->SetRepeatRate(value); }

void Slider::SetFullImageRect()  {  slider_->SetFullImageRect(); }

void Slider::SetHoverOffset(int A, int B)  {  slider_->SetHoverOffset(A, B); }

void Slider::ChangeValue(float A)  {  slider_->ChangeValue(A); }

}
