//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class SmoothedTransform;
    class Vector3;
    class Quaternion;
}



namespace UrhoBackend {


    public ref class SmoothedTransform : public UrhoBackend::Component {
    public:
        SmoothedTransform(Urho3D::SmoothedTransform* comp);
        SmoothedTransform(System::IntPtr^ ptr);

// Properties
        property UrhoBackend::Vector3^ targetPosition { UrhoBackend::Vector3^ get(); void set(UrhoBackend::Vector3^); }
        property UrhoBackend::Quaternion^ targetRotation { UrhoBackend::Quaternion^ get(); void set(UrhoBackend::Quaternion^); }
        property UrhoBackend::Vector3^ targetWorldPosition { UrhoBackend::Vector3^ get(); void set(UrhoBackend::Vector3^); }
        property UrhoBackend::Quaternion^ targetWorldRotation { UrhoBackend::Quaternion^ get(); void set(UrhoBackend::Quaternion^); }
        property bool inProgress { bool get(); }
// Methods
        void Update(float, float);
// Fields

        Urho3D::SmoothedTransform* smoothedtransform_;
    };
}
