//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "SoundListener.h"

#include <Urho3D/Audio/SoundListener.h>

namespace UrhoBackend {

SoundListener::SoundListener(Urho3D::SoundListener* fromUrho) : Component(fromUrho) { soundlistener_ = fromUrho; }
SoundListener::SoundListener(System::IntPtr^ ptr) : SoundListener((Urho3D::SoundListener*)ptr->ToPointer()) { }

}
