//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Spline;
    class Variant;
}

#include <Urho3D/Core/Spline.h>

namespace UrhoBackend {


    public ref class Spline {
    public:
        Spline(Urho3D::Spline comp);
        Spline(System::IntPtr^ ptr);
        ~Spline();

// Properties
        property InterpolationMode interpolationMode { InterpolationMode get(); void set(InterpolationMode); }
        property Variant^ knot[unsigned] { Variant^ get(unsigned); }
// Methods
        Spline^ opAssign(Spline^);
        bool opEquals(Spline^);
        void AddKnot(Variant^);
        void AddKnot(Variant^, unsigned);
        void RemoveKnot();
        void RemoveKnot(unsigned);
        void Clear();
        Variant^ GetPoint(float);
// Fields

        Urho3D::Spline* spline_;
    };
}
