//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class SpriteSheet2D;
    class Sprite2D;
    class String;
    class IntRect;
    class Vector2;
    class IntVector2;
    class Texture2D;
}

#include "Resource.h"

namespace UrhoBackend {

    ref class Sprite2D;
    ref class Texture2D;

    public ref class SpriteSheet2D : public UrhoBackend::Resource {
    public:
        SpriteSheet2D(Urho3D::SpriteSheet2D* comp);
        SpriteSheet2D(System::IntPtr^ ptr);

// Properties
        property Texture2D^ texture { Texture2D^ get(); }
// Methods
        Sprite2D^ GetSprite(System::String^);
        void DefineSprite(System::String^, UrhoBackend::IntRect^, UrhoBackend::Vector2^, UrhoBackend::IntVector2^);
// Fields

        Urho3D::SpriteSheet2D* spritesheet2d_;
    };
}
