//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Sprite2D.h"

#include <Urho3D/Urho2D/Sprite2D.h>
#include <Urho3D/Graphics/Texture2D.h>
#include "Texture2D.h"

namespace UrhoBackend {

Sprite2D::Sprite2D(Urho3D::Sprite2D* fromUrho) : Resource(fromUrho) { sprite2d_ = fromUrho; }
Sprite2D::Sprite2D(System::IntPtr^ ptr) : Sprite2D((Urho3D::Sprite2D*)ptr->ToPointer()) { }

Texture2D^ Sprite2D::texture::get() { return gcnew UrhoBackend::Texture2D(sprite2d_->GetTexture()); }
void Sprite2D::texture::set(Texture2D^ value) { sprite2d_->SetTexture(value->texture2d_); }

UrhoBackend::IntRect^ Sprite2D::rectangle::get() { return gcnew UrhoBackend::IntRect(sprite2d_->GetRectangle()); }
void Sprite2D::rectangle::set(UrhoBackend::IntRect^ value) { sprite2d_->SetRectangle(value->ToIntRect()); }

UrhoBackend::Vector2^ Sprite2D::hotSpot::get() { return gcnew UrhoBackend::Vector2(sprite2d_->GetHotSpot()); }
void Sprite2D::hotSpot::set(UrhoBackend::Vector2^ value) { sprite2d_->SetHotSpot(value->ToVector2()); }

UrhoBackend::IntVector2^ Sprite2D::offset::get() { return gcnew UrhoBackend::IntVector2(sprite2d_->GetOffset()); }
void Sprite2D::offset::set(UrhoBackend::IntVector2^ value) { sprite2d_->SetOffset(value->ToIntVector2()); }

}
