//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Texture;
    class Color;
}

#include "Resource.h"

namespace UrhoBackend {


    public ref class Texture : public UrhoBackend::Resource {
    public:
        Texture(Urho3D::Texture* comp);
        Texture(System::IntPtr^ ptr);

// Properties
        property TextureUsage usage { TextureUsage get(); }
        property unsigned format { unsigned get(); }
        property bool compressed { bool get(); }
        property unsigned levels { unsigned get(); }
        property int width { int get(); }
        property int height { int get(); }
        property int levelWidth[unsigned] { int get(unsigned); }
        property int levelHeight[unsigned] { int get(unsigned); }
        property TextureFilterMode filterMode { TextureFilterMode get(); void set(TextureFilterMode); }
        property TextureAddressMode addressMode[TextureCoordinate] { TextureAddressMode get(TextureCoordinate); void set(TextureCoordinate, TextureAddressMode); }
        property UrhoBackend::Color^ borderColor { UrhoBackend::Color^ get(); void set(UrhoBackend::Color^); }
        property bool sRGB { bool get(); void set(bool); }
        property Texture^ backupTexture { Texture^ get(); void set(Texture^); }
        property int mipsToSkip[int] { int get(int); void set(int, int); }
        property bool dataLost { bool get(); }
// Methods
        void SetNumLevels(unsigned);
        void ClearDataLost();
// Fields

        Urho3D::Texture* texture_;
    };
}
