//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Texture3D.h"

#include <Urho3D/Graphics/Texture3D.h>
#include <Urho3D/Graphics/RenderSurface.h>
#include "RenderSurface.h"
#include <Urho3D/Graphics/GraphicsDefs.h>

namespace UrhoBackend {

Texture3D::Texture3D(Urho3D::Texture3D* fromUrho) : Texture(fromUrho) { texture3d_ = fromUrho; }
Texture3D::Texture3D(System::IntPtr^ ptr) : Texture3D((Urho3D::Texture3D*)ptr->ToPointer()) { }

RenderSurface^ Texture3D::renderSurface::get() { return gcnew UrhoBackend::RenderSurface(texture3d_->GetRenderSurface()); }
bool Texture3D::SetSize(int A, int B, unsigned C, TextureUsage usage)  { return  texture3d_->SetSize(A, B, C, (Urho3D::TextureUsage)usage); }

}
