//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class TextureCube;
    class RenderSurface;
}

#include "Texture.h"

namespace UrhoBackend {

    ref class RenderSurface;

    public ref class TextureCube : public UrhoBackend::Texture {
    public:
        TextureCube(Urho3D::TextureCube* comp);
        TextureCube(System::IntPtr^ ptr);

// Properties
        property RenderSurface^ renderSurfaces[CubeMapFace] { RenderSurface^ get(CubeMapFace); }
// Methods
        bool SetSize(int, unsigned, TextureUsage);
// Fields

        Urho3D::TextureCube* texturecube_;
    };
}
