//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Texture2D.h"

#include <Urho3D/Graphics/Texture2D.h>
#include <Urho3D/Graphics/RenderSurface.h>
#include "RenderSurface.h"
#include <Urho3D/Graphics/GraphicsDefs.h>

namespace UrhoBackend {

Texture2D::Texture2D(Urho3D::Texture2D* fromUrho) : Texture(fromUrho) { texture2d_ = fromUrho; }
Texture2D::Texture2D(System::IntPtr^ ptr) : Texture2D((Urho3D::Texture2D*)ptr->ToPointer()) { }

RenderSurface^ Texture2D::renderSurface::get() { return gcnew UrhoBackend::RenderSurface(texture2d_->GetRenderSurface()); }
bool Texture2D::SetSize(int A, int B, unsigned C, TextureUsage usage)  { return  texture2d_->SetSize(A, B, C, (Urho3D::TextureUsage)usage); }

}
