//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Tile2D;
    class String;
    class Sprite2D;
}



namespace UrhoBackend {

    ref class Sprite2D;

    public ref class Tile2D : public UrhoBackend::RefCounted {
    public:
        Tile2D(Urho3D::Tile2D* comp);
        Tile2D(System::IntPtr^ ptr);

// Properties
        property int gid { int get(); }
        property Sprite2D^ sprite { Sprite2D^ get(); }
// Methods
        bool HasProperty(System::String^);
        System::String^ GetProperty(System::String^);
// Fields

        Urho3D::Tile2D* tile2d_;
    };
}
