//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "Tile2D.h"

#include <Urho3D/Urho2D/TileMapDefs2D.h>
#include <Urho3D/Urho2D/Sprite2D.h>
#include "Sprite2D.h"

namespace UrhoBackend {

Tile2D::Tile2D(Urho3D::Tile2D* fromUrho) : RefCounted(fromUrho) { tile2d_ = fromUrho; }
Tile2D::Tile2D(System::IntPtr^ ptr) : Tile2D((Urho3D::Tile2D*)ptr->ToPointer()) { }

int Tile2D::gid::get() { return tile2d_->GetGid(); }
Sprite2D^ Tile2D::sprite::get() { return gcnew UrhoBackend::Sprite2D(tile2d_->GetSprite()); }
bool Tile2D::HasProperty(System::String^ A)  { return  tile2d_->HasProperty(Urho3D::String(ToCString(A))); }

System::String^ Tile2D::GetProperty(System::String^ A)  { return  gcnew System::String(tile2d_->HasProperty(Urho3D::String(ToCString(A))).CString()); }

}
