//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class TileMapObject2D;
    class Vector2;
    class String;
    class Sprite2D;
}



namespace UrhoBackend {

    ref class Sprite2D;

    public ref class TileMapObject2D : public UrhoBackend::RefCounted {
    public:
        TileMapObject2D(Urho3D::TileMapObject2D* comp);
        TileMapObject2D(System::IntPtr^ ptr);

// Properties
        property TileObjectType2D objectType { TileObjectType2D get(); }
        property System::String^ name { System::String^ get(); }
        property System::String^ type { System::String^ get(); }
        property UrhoBackend::Vector2^ position { UrhoBackend::Vector2^ get(); }
        property UrhoBackend::Vector2^ size { UrhoBackend::Vector2^ get(); }
        property unsigned numPoints { unsigned get(); }
        property int tileGid { int get(); }
        property Sprite2D^ tileSprite { Sprite2D^ get(); }
// Methods
        UrhoBackend::Vector2^ GetPoint(unsigned);
        bool HasProperty(System::String^);
        System::String^ GetProperty(System::String^);
// Fields

        Urho3D::TileMapObject2D* tilemapobject2d_;
    };
}
