//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "TileMap2D.h"

#include <Urho3D/Urho2D/TileMap2D.h>
#include <Urho3D/Urho2D/TileMapLayer2D.h>
#include "TileMapLayer2D.h"
#include <Urho3D/Urho2D/TmxFile2D.h>
#include "TmxFile2D.h"
#include <Urho3D/Urho2D/TileMapDefs2D.h>
#include "TileMapInfo2D.h"

namespace UrhoBackend {

TileMap2D::TileMap2D(Urho3D::TileMap2D* fromUrho) : Component(fromUrho) { tilemap2d_ = fromUrho; }
TileMap2D::TileMap2D(System::IntPtr^ ptr) : TileMap2D((Urho3D::TileMap2D*)ptr->ToPointer()) { }

TmxFile2D^ TileMap2D::tmxFile::get() { return gcnew UrhoBackend::TmxFile2D(tilemap2d_->GetTmxFile()); }
void TileMap2D::tmxFile::set(TmxFile2D^ value) { tilemap2d_->SetTmxFile(value->tmxfile2d_); }

TileMapInfo2D^ TileMap2D::info::get() { return gcnew UrhoBackend::TileMapInfo2D(tilemap2d_->GetInfo()); }
unsigned TileMap2D::numLayers::get() { return tilemap2d_->GetNumLayers(); }
TileMapLayer2D^ TileMap2D::GetLayer(unsigned A)  { return  gcnew UrhoBackend::TileMapLayer2D(tilemap2d_->GetLayer(A)); }

UrhoBackend::Vector2^ TileMap2D::TileIndexToPosition(int A, int B)  { return  gcnew UrhoBackend::Vector2(tilemap2d_->TileIndexToPosition(A, B)); }

bool TileMap2D::PositionToTileIndex(intout x A, int out y B, UrhoBackend::Vector2^ C)  { return  tilemap2d_->PositionToTileIndex(A, B, C->ToVector2()); }

}
