//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class TileMapLayer2D;
    class String;
    class Tile2D;
    class Node;
    class TileMapObject2D;
}



namespace UrhoBackend {

    ref class Tile2D;
    ref class TileMapObject2D;

    public ref class TileMapLayer2D : public UrhoBackend::Component {
    public:
        TileMapLayer2D(Urho3D::TileMapLayer2D* comp);
        TileMapLayer2D(System::IntPtr^ ptr);

// Properties
        property int drawOrder { int get(); void set(int); }
        property bool visible { bool get(); void set(bool); }
        property TileMapLayerType2D layerType { TileMapLayerType2D get(); }
        property int width { int get(); }
        property int height { int get(); }
        property unsigned numObjects { unsigned get(); }
        property Node^ imageNode { Node^ get(); }
// Methods
        bool HasProperty(System::String^);
        System::String^ GetProperty(System::String^);
        Tile2D^ GetTile(int, int);
        Node^ GetTileNode(int, int);
        TileMapObject2D^ GetObject(unsigned);
        Node^ GetObjectNode(unsigned);
// Fields

        Urho3D::TileMapLayer2D* tilemaplayer2d_;
    };
}
