//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class TileMapInfo2D;
}

#include <Urho3D/Urho2D/TileMapDefs2D.h>

namespace UrhoBackend {


    public ref class TileMapInfo2D {
    public:
        TileMapInfo2D(Urho3D::TileMapInfo2D comp);
        TileMapInfo2D(System::IntPtr^ ptr);
        ~TileMapInfo2D();

// Properties
        property float mapWidth { float get(); }
        property float mapHeight { float get(); }
// Methods
// Fields
        property Orientation2D orientation { Orientation2D get(); void set(Orientation2D value); }
        property int width { int get(); void set(int value); }
        property int height { int get(); void set(int value); }
        property float tileWidth { float get(); void set(float value); }
        property float tileHeight { float get(); void set(float value); }

        Urho3D::TileMapInfo2D* tilemapinfo2d_;
    };
}
