//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class TileMap2D;
    class TileMapLayer2D;
    class Vector2;
    class TmxFile2D;
    class TileMapInfo2D;
}



namespace UrhoBackend {

    ref class TileMapLayer2D;
    ref class TmxFile2D;
    ref class TileMapInfo2D;

    public ref class TileMap2D : public UrhoBackend::Component {
    public:
        TileMap2D(Urho3D::TileMap2D* comp);
        TileMap2D(System::IntPtr^ ptr);

// Properties
        property TmxFile2D^ tmxFile { TmxFile2D^ get(); void set(TmxFile2D^); }
        property TileMapInfo2D^ info { TileMapInfo2D^ get(); }
        property unsigned numLayers { unsigned get(); }
// Methods
        TileMapLayer2D^ GetLayer(unsigned);
        UrhoBackend::Vector2^ TileIndexToPosition(int, int);
        bool PositionToTileIndex(intout x, int out y, UrhoBackend::Vector2^);
// Fields

        Urho3D::TileMap2D* tilemap2d_;
    };
}
