//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Time;
}



namespace UrhoBackend {


    public ref class Time : public UrhoBackend::Object {
    public:
        Time(Urho3D::Time* comp);
        Time(System::IntPtr^ ptr);

// Properties
        property unsigned frameNumber { unsigned get(); }
        property float timeStep { float get(); }
        property float elapsedTime { float get(); }
// Methods
// Fields

        Urho3D::Time* time_;
    };
}
