//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class TmxFile2D;
}

#include "Resource.h"

namespace UrhoBackend {


    public ref class TmxFile2D : public UrhoBackend::Resource {
    public:
        TmxFile2D(Urho3D::TmxFile2D* comp);
        TmxFile2D(System::IntPtr^ ptr);

// Properties
// Methods
// Fields

        Urho3D::TmxFile2D* tmxfile2d_;
    };
}
