//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class TouchState;
    class UIElement;
    class IntVector2;
}

#include <Urho3D/Input/Input.h>

namespace UrhoBackend {

    ref class UIElement;

    public ref class TouchState {
    public:
        TouchState(Urho3D::TouchState comp);
        TouchState(System::IntPtr^ ptr);
        ~TouchState();

// Properties
        property UIElement^ touchedElement { UIElement^ get(); }
// Methods
// Fields
        property int touchID { int get(); void set(int value); }
        property UrhoBackend::IntVector2^ position { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^ value); }
        property UrhoBackend::IntVector2^ lastPosition { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^ value); }
        property UrhoBackend::IntVector2^ delta { UrhoBackend::IntVector2^ get(); void set(UrhoBackend::IntVector2^ value); }
        property float pressure { float get(); void set(float value); }

        Urho3D::TouchState* touchstate_;
    };
}
