//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "TouchState.h"

#include <Urho3D/Input/Input.h>
#include <Urho3D/UI/UIElement.h>
#include "UIElement.h"

namespace UrhoBackend {

TouchState::TouchState(Urho3D::TouchState fromUrho) { touchstate_ = new Urho3D::TouchState(); *touchstate_ = fromUrho; }
TouchState::TouchState(System::IntPtr^ ptr) : TouchState(*((Urho3D::TouchState*)ptr->ToPointer())) { }
TouchState::~TouchState() { delete touchstate_; }
UIElement^ TouchState::touchedElement::get() { return gcnew UrhoBackend::UIElement(touchstate_->GetTouchedElement()); }
int TouchState::touchID::get() { return touchstate_->touchID_; }
void TouchState::touchID::set(int value) { touchstate_->touchID_ = value; }

UrhoBackend::IntVector2^ TouchState::position::get() { return gcnew UrhoBackend::IntVector2(touchstate_->position_); }
void TouchState::position::set(UrhoBackend::IntVector2^ value) { touchstate_->position_ = value->ToIntVector2(); }

UrhoBackend::IntVector2^ TouchState::lastPosition::get() { return gcnew UrhoBackend::IntVector2(touchstate_->lastPosition_); }
void TouchState::lastPosition::set(UrhoBackend::IntVector2^ value) { touchstate_->lastPosition_ = value->ToIntVector2(); }

UrhoBackend::IntVector2^ TouchState::delta::get() { return gcnew UrhoBackend::IntVector2(touchstate_->delta_); }
void TouchState::delta::set(UrhoBackend::IntVector2^ value) { touchstate_->delta_ = value->ToIntVector2(); }

float TouchState::pressure::get() { return touchstate_->pressure_; }
void TouchState::pressure::set(float value) { touchstate_->pressure_ = value; }

}
