//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Viewport;
    class XMLFile;
    class Ray;
    class Vector2;
    class Vector3;
    class Scene;
    class Camera;
    class RenderPath;
    class IntRect;
}



namespace UrhoBackend {

    ref class XMLFile;
    ref class Ray;
    ref class Camera;
    ref class RenderPath;

    public ref class Viewport : public UrhoBackend::UObject {
    public:
        Viewport(Urho3D::Viewport* comp);
        Viewport(System::IntPtr^ ptr);

// Properties
        property Scene^ scene { Scene^ get(); void set(Scene^); }
        property Camera^ camera { Camera^ get(); void set(Camera^); }
        property RenderPath^ renderPath { RenderPath^ get(); void set(RenderPath^); }
        property UrhoBackend::IntRect^ rect { UrhoBackend::IntRect^ get(); void set(UrhoBackend::IntRect^); }
        property bool drawDebug { bool get(); void set(bool); }
// Methods
        void SetRenderPath(XMLFile^);
        Ray^ GetScreenRay(int, int);
        UrhoBackend::Vector2^ WorldToScreenPoint(UrhoBackend::Vector3^);
        UrhoBackend::Vector3^ ScreenToWorldPoint(int, int, float);
// Fields

        Urho3D::Viewport* viewport_;
    };
}
