//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "View3D.h"

#include <Urho3D/UI/View3D.h>
#include <Urho3D/Graphics/Camera.h>
#include "Camera.h"
#include <Urho3D/Graphics/Texture2D.h>
#include "Texture2D.h"
#include <Urho3D/Graphics/Viewport.h>
#include "Viewport.h"

namespace UrhoBackend {

View3D::View3D(Urho3D::View3D* fromUrho) : UIElement(fromUrho) { view3d_ = fromUrho; }
View3D::View3D(System::IntPtr^ ptr) : View3D((Urho3D::View3D*)ptr->ToPointer()) { }

void View3D::fixedWidthResizing::set(bool value) { view3d_->SetFixedWidthResizing(value); }

void View3D::fixedHeightResizing::set(bool value) { view3d_->SetFixedHeightResizing(value); }

bool View3D::movable::get() { return view3d_->IsMovable(); }
void View3D::movable::set(bool value) { view3d_->SetMovable(value); }

bool View3D::resizable::get() { return view3d_->IsResizable(); }
void View3D::resizable::set(bool value) { view3d_->SetResizable(value); }

UrhoBackend::IntRect^ View3D::resizeBorder::get() { return gcnew UrhoBackend::IntRect(view3d_->GetResizeBorder()); }
void View3D::resizeBorder::set(UrhoBackend::IntRect^ value) { view3d_->SetResizeBorder(value->ToIntRect()); }

bool View3D::modal::get() { return view3d_->IsModal(); }
void View3D::modal::set(bool value) { view3d_->SetModal(value); }

UrhoBackend::Color^ View3D::modalShadeColor::get() { return gcnew Color(view3d_->GetModalShadeColor()); }
void View3D::modalShadeColor::set(UrhoBackend::Color^ value) { view3d_->SetModalShadeColor(value->ToColor()); }

UrhoBackend::Color^ View3D::modalFrameColor::get() { return gcnew Color(view3d_->GetModalFrameColor()); }
void View3D::modalFrameColor::set(UrhoBackend::Color^ value) { view3d_->SetModalFrameColor(value->ToColor()); }

UrhoBackend::IntVector2^ View3D::modalFrameSize::get() { return gcnew UrhoBackend::IntVector2(view3d_->GetModalFrameSize()); }
void View3D::modalFrameSize::set(UrhoBackend::IntVector2^ value) { view3d_->SetModalFrameSize(value->ToIntVector2()); }

bool View3D::modalAutoDismiss::get() { return view3d_->GetModalAutoDismiss(); }
void View3D::modalAutoDismiss::set(bool value) { view3d_->SetModalAutoDismiss(value); }

bool View3D::fixedWidthResizing::get() { return view3d_->GetFixedWidthResizing(); }
bool View3D::fixedHeightResizing::get() { return view3d_->GetFixedHeightResizing(); }
unsigned View3D::format::get() { return view3d_->GetFormat(); }
void View3D::format::set(unsigned value) { view3d_->SetFormat(value); }

bool View3D::autoUpdate::get() { return view3d_->GetAutoUpdate(); }
void View3D::autoUpdate::set(bool value) { view3d_->SetAutoUpdate(value); }

Texture2D^ View3D::renderTexture::get() { return gcnew UrhoBackend::Texture2D(view3d_->GetRenderTexture()); }
Texture2D^ View3D::depthTexture::get() { return gcnew UrhoBackend::Texture2D(view3d_->GetDepthTexture()); }
Viewport^ View3D::viewport::get() { return gcnew UrhoBackend::Viewport(view3d_->GetViewport()); }
Scene^ View3D::scene::get() { return gcnew UrhoBackend::Scene(view3d_->GetScene()); }
Node^ View3D::cameraNode::get() { return gcnew UrhoBackend::Node(view3d_->GetCameraNode()); }
void View3D::SetView(Scene^ A, Camera^ B, bool ownScen)  {  view3d_->SetView(A->scene_, B->camera_, ownScen); }

void View3D::QueueUpdate()  {  view3d_->QueueUpdate(); }

}
