//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#include "stdafx.h"
#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include <Urho3D/Container/Str.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../UrControl.h"
#include "WeakHandle.h"

#include <Urho3D/Container/RefCounted.h>
#include "RefCounted.h"

namespace UrhoBackend {

WeakHandle::WeakHandle(Urho3D::WeakHandle fromUrho) { weakhandle_ = new Urho3D::WeakHandle(); *weakhandle_ = fromUrho; }
WeakHandle::WeakHandle(System::IntPtr^ ptr) : WeakHandle(*((Urho3D::WeakHandle*)ptr->ToPointer())) { }
WeakHandle::~WeakHandle() { delete weakhandle_; }
int WeakHandle::refs::get() { return weakhandle_->Refs(); }
int WeakHandle::weakRefs::get() { return weakhandle_->WeakRefs(); }
bool WeakHandle::expired::get() { return weakhandle_->Expired(); }
WeakPtr<RefCounted> WeakHandle::opAssign(WeakHandle^ A)  { return  weakhandle_->operator =(*A->weakhandle_); }

WeakPtr<RefCounted> WeakHandle::opAssign(RefCounted^ A)  { return  weakhandle_->operator =(A->refcounted_); }

RefCounted^ WeakHandle::Get()  { return  gcnew UrhoBackend::RefCounted(weakhandle_->Get()); }

}
