//THIS FILE IS AUTOGENERATED - DO NOT MODIFY
#pragma once

#include <Urho3D/Urho3D.h>
#include <Urho3D/Scene/Component.h>
#include "../MathBind.h"
#include "../ResourceRefWrapper.h"
#include "../SceneWrappers.h"
#include "../Variant.h"
#include "../StringHash.h"
#include "../Attributes.h"

#include "Enumerations.h"

namespace Urho3D {
    class Zone;
    class BoundingBox;
    class Matrix3x4;
    class Color;
    class Texture;
}

#include "Drawable.h"

namespace UrhoBackend {

    ref class BoundingBox;
    ref class Texture;

    public ref class Zone : public UrhoBackend::Drawable {
    public:
        Zone(Urho3D::Zone* comp);
        Zone(System::IntPtr^ ptr);

// Properties
        property bool override { void set(bool); }
        property BoundingBox^ boundingBox { void set(BoundingBox^); }
        property UrhoBackend::Matrix3x4^ inverseWorldTransform { UrhoBackend::Matrix3x4^ get(); }
        property UrhoBackend::Color^ ambientColor { UrhoBackend::Color^ get(); void set(UrhoBackend::Color^); }
        property UrhoBackend::Color^ ambientStartColor { UrhoBackend::Color^ get(); }
        property UrhoBackend::Color^ ambientEndColor { UrhoBackend::Color^ get(); }
        property UrhoBackend::Color^ fogColor { UrhoBackend::Color^ get(); void set(UrhoBackend::Color^); }
        property float fogStart { float get(); void set(float); }
        property float fogEnd { float get(); void set(float); }
        property float fogHeight { float get(); void set(float); }
        property float fogHeightScale { float get(); void set(float); }
        property int priority { int get(); void set(int); }
        property bool heightFog { bool get(); void set(bool); }
        property bool override { bool get(); }
        property bool ambientGradient { bool get(); void set(bool); }
        property Texture^ zoneTexture { Texture^ get(); void set(Texture^); }
// Methods
// Fields

        Urho3D::Zone* zone_;
    };
}
